### ISSUE TITLE
keyup.enter error

### ISSUE THREAD

**Issue by willwalker** [gmerabishvili/angular-ng-autocomplete#1]
I resolve with Viewchild. Thanks

**Comment by gmerabishvili** [comment]
Thanks for reporting the issue. But can you give me further details about the issue so I'll fix it?

**Comment by willwalker** [comment]
Hi! I am continue with this problem:

I want use keyboard for select the item and when i press enter, change de value output for call function selected. Can you fix it? For me thats it.

**Comment by gmerabishvili** [comment]
So when you want to change the selected value after press enter?

**Comment by willwalker** [comment]
Yes, i want use the arrow buttons in my keyboard, when i press enter, chance the value input endereço emit the selected.

**Comment by willwalker** [comment]
Yes! Because i want use keyboard for select the value and press enter for change value input and output **selected**. Can you fix it?

**Comment by gmerabishvili** [comment]
Hello, the issue is resolved. Please update to latest 1.0.3 version. Thank you!

**Comment by willwalker** [comment]
I test and not happen when i press enter, see this video: https://www.4shared.com/video/Q928Ip0see/2019-01-29_17-29-59.html

I want select the value and execute the function output: https://www.4shared.com/photo/pSHlC5xXda/2019-01-29_17-34-13.html

**Comment by willwalker** [comment]
I test and works perfect! Thank you! You are the best!
