### ISSUE TITLE
Edge/IE Keyboard selection of values not working

### ISSUE THREAD

**Issue by RemDev8** [gmerabishvili/angular-ng-autocomplete#10]
When using IE or Edge with this component the keyboard up/down arrows cannot be used to focus values from the filtered list for selection with the enter key. This works as expected in chrome.

This behaviour can be replicated using the example page for this component: https://gmerabishvili.github.io/angular-ng-autocomplete/

Is it possible to add this compatibility with the Microsoft browsers?

**Comment by gmerabishvili** [comment]
Hello, The issue is resolved. Please update to latest 1.1.14 version. Thank you!
