### ISSUE TITLE
(scrolledToEnd) triggered twice when you scrolled on results

### ISSUE THREAD

**Issue by yoyo497** [gmerabishvili/angular-ng-autocomplete#101]
Once I do a search and scroll between my results ( even 1 pixel ) and change the search string, the (scrolledToEnd) event is triggered twice. When you scroll between results but make sure you scroll back to the top, (scrolledToEnd) is triggered once.

**Comment by gmerabishvili** [comment]
@yoyo497 Hello, can you provide Stackblitz example on this one please? I tested and it works normally. Closing this issue for now. Thank you.
