### ISSUE TITLE
debounceTime type has been defined as "400" instead of "number"

### ISSUE THREAD

**Issue by masoudtahmasebi93** [gmerabishvili/angular-ng-autocomplete#103]
Hi, in the "autocomplete.component.d.ts" the `debounceTime` input has been set as "400", while according to the documentation its type should be number with the default number of 400.
what it is:
`debounceTime: 400;`

what it should be:

`debounceTime: number;`

P.S I searched all issues and didn't find that

**Comment by gmerabishvili** [comment]
Hello @masoudtahmasebi93 The issue is fixed. Please upgrade to latest 2.0.2 version. Thank you!
