### ISSUE TITLE
generated input is not ng-invalig on invalid validator in formreactive

### ISSUE THREAD

**Issue by BrunoMrlls** [gmerabishvili/angular-ng-autocomplete#104]
hello, I wonder if there is a way to force the generated input to be ng-valid / ng-invalid? I need to change the input css according to validators of form reactive angular 8.

thanks

**Comment by gmerabishvili** [comment]
Hello, can you provide. more details about your requirement?

**Comment by BrunoMrlls** [comment]
@gmerabishvili thanks, i resolve problem adding display:block in my css. Your compomenent is very good. sorry for my inglish kkkk
