### ISSUE TITLE
TypeError: Cannot read property 'toLowerCase' of undefined at angular-ng-autocomplete.js:309

### ISSUE THREAD

**Issue by haroon786** [gmerabishvili/angular-ng-autocomplete#106]
Hi, I was implementing  angular-ng-autocomplete , and I used two times with two different two keywords. Can't we used two ng autocomplete in single component. I am trying to bind from API call , please let me the solution

**Comment by gmerabishvili** [comment]
@haroon786 Yes, you can use two ng autocompletes in a single component.
