### ISSUE TITLE
inputChanged event is getting triggered but getting event variable undefined

### ISSUE THREAD

**Issue by devashishg** [gmerabishvili/angular-ng-autocomplete#109]
In my developmment environment when I am using this component for to autosuggest with api integeration, I triggered the inputchanged event but but when it triggers it gives undefined value for event variable passed on function call.

```
<ng-autocomplete
      [data]="myObs | async"
      [searchKeyword]="searchKeyword"
      placeHolder="Enter the {{ Title}}"
      (input)="onChangeSearch($event)"
      (selected)="selectEvent($event)"
      (inputCleared)= "clearAuto()"
      (inputChanged)="ChangeSearch($event)"
      [isLoading] = "isLoadingCNO"
      [itemTemplate]="itemTemplate"
      [notFoundTemplate]="notFoundTemplate"
      >
    </ng-autocomplete> 
```
For the sake of this to work, I added input event.

But here
Another issue I am facing is when the Observable data changes and initially observable was loaded with empty array then this keep showing me results not found until i type another key.
e.g. I type 'a' it sends api req. and get results that are loaded in observable but that "no result found" message still shows and not changes the template to _itemTemplate_
once I type another key or ctrl+space then it shows me old api response data.

I hope i made my problem statement clear. Please someone help me on this.

**Comment by gmerabishvili** [comment]
@devashishg Hey, is this issue still persists?

**Comment by gmerabishvili** [comment]
@devashishg Hello, tested and couldn't replicate any of these issues. The problem is definitely on your implementation. Thank you.
