### ISSUE TITLE
[searcKeyword] functionality

### ISSUE THREAD

**Issue by ljunokas** [gmerabishvili/angular-ng-autocomplete#11]
Hi, is it possible to ignore search keyword functionality, because i do search logic in backend, and i search by multiple criteria, so if user enters short name, i cant display it because its not the same as full name

**Comment by gmerabishvili** [comment]
Hi, I don't think it is possible, because you'll need some property to filter data with in any case...

**Comment by ljunokas** [comment]
Well i do all the filtering in the backend, and i use your module for showing it thats all :)

**Comment by gmerabishvili** [comment]
That's great! : )
