### ISSUE TITLE
Avoid list reload on emptied input

### ISSUE THREAD

**Issue by JhonMyHW** [gmerabishvili/angular-ng-autocomplete#110]
Hi there!

Is there a way to avoid ng-autocomplete to reload the data list when field is cleared?

I have a very long set of data (9k elements) that has no expected relevant results if searched words aren't longer than 3 characters at least.

Since it takes a few secs to load the full 9k elements list, I wanted the ng-autocomplete to avoid loading the data list until the input is at least 3 characters long, resulting in faster loads.

I set the [minQueryLength] property to 3, so I was expecting it to only search and reload the list elements when input is at least 3 characters long.

Although, when I clear the field, aka 0 characters long input, the list is reloaded showing the full set of data.

Is there a way to avoid that?

Thanks in advance for your kind support!

**Comment by manojvarmaboppisetti** [comment]
hey @JhonMyHW just set data object to empty array ( i.e []) and stop making any api calls to fetch data.

**Comment by gmerabishvili** [comment]
@JhonMyHW Yeah, you can just set data to empty array on input clear or use Infinite scroll to load items in chunks.
