### ISSUE TITLE
How To Use The "Methods"?

### ISSUE THREAD

**Issue by JimLynchCodes** [gmerabishvili/angular-ng-autocomplete#111]
At the very end of the README there is a mention of these functions:

```
 openPanel(e): void {
    e.stopPropagation();
    this.auto.open();
  }
  
  closePanel(e): void {
    e.stopPropagation();
    this.auto.close();
    }
    
  focus(e): void {
    e.stopPropagation();
    this.auto.focus();
  }  
```

How are these functions supposed to be called? Where are they used?

It's currently very confusing. I think it would be nice to add some clarification to the docs here....

Thanks!

**Comment by shtaimoortariq** [comment]
+
