### ISSUE TITLE
Error: No value accessor for form control with name

### ISSUE THREAD

**Issue by JimLynchCodes** [gmerabishvili/angular-ng-autocomplete#115]
Hi, when I try to use "FormControl" or "FormControlName" I just get the error, "ERROR Error: No value accessor for form control with name".

Can someone please explain how to use this? 🤔

**Comment by gmerabishvili** [comment]
@JimLynchCodes Please provide an example please.

**Comment by gmerabishvili** [comment]
@JimLynchCodes Hey, did you fix the issue?
