### ISSUE TITLE
I can't use it.

### ISSUE THREAD

**Issue by moshtaba** [gmerabishvili/angular-ng-autocomplete#116]
**I got this error:**
This likely means that the library (angular-ng-autocomplete/lib/autocomplete-lib.module) which declares AutocompleteLibModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

**Comment by gmerabishvili** [comment]
@moshtaba Hello, the library is compatible with ivy. I think there's some local problem on your project.
