### ISSUE TITLE
Unable to bind data on first API call

### ISSUE THREAD

**Issue by rxa092** [gmerabishvili/angular-ng-autocomplete#117]
I am having trouble binding data on first try from ajax call. The data is present in the list but it shows nothing. When I press backspace it shows the data. After one time it is working correctly. How can this issue be resolved

**Comment by gmerabishvili** [comment]
@rxa092 Can you provide an example please?

**Comment by rxa092** [comment]
code example ?

**Comment by gmerabishvili** [comment]
@rxa092 Yes. You can use Stackblitz.

**Comment by gmerabishvili** [comment]
@rxa092 Hey, did you fix the issue?

**Comment by almgwary** [comment]
issue confirmed 
first API call doesn't open the drop menu, it sets this.data but not the  this.filteredList

**Comment by almgwary** [comment]
fixed 🎈 after removing middle-ware binding `[data]="options"` from middle-ware component


 ```

<app-middle-ware
  formControlName="city"
  [data]="options" // remove this parent binding if you are loading data from a middle-ware component
  [search]="element.search" >
      <ng-autocomplete
        [data]="data"
        [isLoading]="isLoading"
      > </ng-autocomplete>

</app-middle-ware>

```
