### ISSUE TITLE
Instalation error

### ISSUE THREAD

**Issue by kevintrujillom** [gmerabishvili/angular-ng-autocomplete#118]
**Hi, I'm new to developing in angular and when trying to install ng-autocomplete I see the following error:**

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: soled@0.0.0
npm ERR! Found: tslib@2.0.3
npm ERR! node_modules/tslib
npm ERR!   tslib@"^2.0.0" from the root project
npm ERR!   tslib@"^2.0.0" from @angular/common@10.2.3
npm ERR!   node_modules/@angular/common
npm ERR!     @angular/common@"~10.2.0" from the root project
npm ERR!     peer @angular/common@"*" from angular-ng-autocomplete@2.0.1
npm ERR!     node_modules/angular-ng-autocomplete
npm ERR!       angular-ng-autocomplete@"*" from the root project
npm ERR!   1 more (@angular/core)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer tslib@"^1.10.0" from angular-ng-autocomplete@2.0.1
npm ERR! node_modules/angular-ng-autocomplete
npm ERR!   angular-ng-autocomplete@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See C:\Users\Kev\AppData\Local\npm-cache\eresolve-report.txt for a full report.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Kev\AppData\Local\npm-cache\_logs\2020-11-21T01_04_16_275Z-debug.log

**This is the version of my angular:**

Angular CLI: 10.2.0
Node: 15.0.1
OS: win32 x64

Angular: 10.2.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1002.0
@angular-devkit/build-angular   0.1002.0
@angular-devkit/core            10.2.0
@angular-devkit/schematics      10.2.0
@angular/cli                    10.2.0
@schematics/angular             10.2.0
@schematics/update              0.1002.0
rxjs                            6.6.3
typescript                      4.0.5

I would like to know if ng-complete works with my version of angular or to know what the problem may be. Thanks

**Comment by gmerabishvili** [comment]
@kevintrujillom It should work on your Angular version. I think there's some other problem, not about angular-autocomplete.
