### ISSUE TITLE
Angular Dependencies are set to V6, while the description says Angular +2

### ISSUE THREAD

**Issue by tarazena** [gmerabishvili/angular-ng-autocomplete#12]
When I'm trying to install the package into my project (running Angular 5), I'm getting an error for missing peer dependency
```
npm ERR! peer dep missing: @angular/common@^6.0.0-rc.0 || ^6.0.0, required by angular-ng-autocomplete@1.1.12
npm ERR! peer dep missing: @angular/core@^6.0.0-rc.0 || ^6.0.0, required by angular-ng-autocomplete@1.1.12
```
Can the dependency versions lowered?

**Comment by gmerabishvili** [comment]
Hello, I think you must update your angular app to at least angular 6 or angular 7 version. Unfortunately angular library, which is new in angular 6 and angular 7 is not backwards compatible with NG 5 and below...
