### ISSUE TITLE
Unable to set Default Value during run time

### ISSUE THREAD

**Issue by lalkumar1020** [gmerabishvili/angular-ng-autocomplete#123]
1. Initial value has been set when we declare itself
2. After getting values from server (during run time)the initial value have to be reset

**Comment by gmerabishvili** [comment]
@lalkumar1020 Hello, can you provide an example in Stackblitz?

**Comment by gmerabishvili** [comment]
Hey, did you fix the issue?

**Comment by gmerabishvili** [comment]
@lalkumar1020 The issue is fixed. Please upgrade to latest 2.0.3 version. Thank you!
