### ISSUE TITLE
Unable to Clear the value in runtime for template driven forms

### ISSUE THREAD

**Issue by suribalu** [gmerabishvili/angular-ng-autocomplete#124]
#### Bug description
Unable to Clear the textbox value in runtime for template driven forms

#### Expected result

Textbox value should clear at run time

#### Actual result

Value still remains in the textbox.
#### Steps to reproduce

1. Enter some value in textbox 'testingabc'
2. Click on submit button  and check the console "selectedValue displays the testingabc"
3. Click on clear button and check the console "selectedValue displays the  empty, but entered value still remains in textbox"
#### Context

This issue with new version 2.0.2, everything fine with 2.0.1
#### Your Environment

* Version used: 2.0.2
* Browser Name and version:  Chrome
* Operating System and version: Windows 10
* Link to your project: https://stackblitz.com/edit/angular-ng-autocomplete-v8mbqa?file=src%2Fapp%2Fapp.component.ts

**Comment by gmerabishvili** [comment]
Hello @suribalu Thank you for reporting the issue with such detailed explanation. The issue is fixed and you can upgrade to latest 2.0.3 version! <3

**Comment by suribalu** [comment]
Hello @gmerabishvili Thanks for your quick response and fix. I tested it is working fine. 👍
