### ISSUE TITLE
Cannot map new property in [searchKeyword], Strictly we need to map 'name' property in response object

### ISSUE THREAD

**Issue by suribalu** [gmerabishvili/angular-ng-autocomplete#125]
#### Bug description
Cannot map new property in [searchKeyword], Strictly we need to map  'name' property in response object

keyword = 'name';

public countries = [
    {
      id: 1,
      name: 'Albania',
    }
]

#### Expected result

Need to search with new property in [searchKeyword] from the response object.

keyword = 'fullname';

public countries = [
    {
      id: 1,
      fullname: 'Albania',
    }
]

#### Actual result

It hides the text in the dropdown list.

#### Steps to reproduce

1.  Open the provided example.
2.  Click on drop down and check the list of options.
#### Your Environment

* Version used: 2.0.4
* Browser Name and version: Chrome
* Operating System and version: Windows 10
* Link to your project: https://stackblitz.com/edit/angular-ng-autocomplete-kidqyh?file=src%2Fapp%2Fapp.component.ts

**Comment by suribalu** [comment]
Screenshot
![image](https://user-images.githubusercontent.com/26923892/103883553-51e59f00-5118-11eb-968d-42e665941407.png)

**Comment by gmerabishvili** [comment]
Hello @suribalu why don't you use fullname here? `  <ng-template #itemTemplate let-item>
    <a [innerHTML]="item.fullname"></a>
  </ng-template>`
