### ISSUE TITLE
The new version > 2.0.1 not work when change data dinamically

### ISSUE THREAD

**Issue by tonysanrusso** [gmerabishvili/angular-ng-autocomplete#126]
#### Steps to reproduce

1.
2.
3.
#### Your Environment

* Version used:
* Browser Name and version:
* Operating System and version:
* Link to your project:

**Comment by gmerabishvili** [comment]
@tonysanrusso What do you mean? Can you provide more details?

**Comment by tonysanrusso** [comment]
Hi!,

Of course, when I change the [data] dynamically eg. into in service
.subscribe(res ... the template with results not show the results, the data
.. with versions < 2.0.2 work fine..

Regards.

**Comment by gmerabishvili** [comment]
@tonysanrusso  Can you show me the code?

**Comment by gmerabishvili** [comment]
@tonysanrusso  Here is the working demo when I fetch data dynamically from the API: https://stackblitz.com/edit/angular-ivy-qjhygd?file=src%2Fapp%2Fapp.component.html

**Comment by tonysanrusso** [comment]
Hi,

In two or three hours I send you the code.. ok?

Thank you very much!

**Comment by tonysanrusso** [comment]
Do you have zoom?

**Comment by gmerabishvili** [comment]
@tonysanrusso Okay.

**Comment by gmerabishvili** [comment]
@tonysanrusso yes.

**Comment by tonysanrusso** [comment]
Hello!,

If want we see it by zoom,

**Comment by gmerabishvili** [comment]
@tonysanrusso let me know when you'll be available. You can write me on  Linkedin : https://www.linkedin.com/in/gio-mera/ Thank you.

**Comment by tonysanrusso** [comment]
When you want.

**Comment by gmerabishvili** [comment]
@tonysanrusso  Hello, are you available today?

**Comment by gmerabishvili** [comment]
@tonysanrusso Couldn't replicate the issue. So, I'm closing it for now.
