### ISSUE TITLE
Feature request: Ignore filtered list and preserve that.

### ISSUE THREAD

**Issue by mncorreialive** [gmerabishvili/angular-ng-autocomplete#128]
Hello, I'm Matheus, a Brazilian Angular Developer and I have an feature idea to help me and another user.

#### Is your feature request related to a problem? Please describe.
I've an UX problem when user type they keywords and my website recover ordered data by type (because is a trip destination autocomplete) from my WebAPI and the ng-autocomplete component reordered this same data, and this as a problem because the data is just "ordered" and "filtered" from WebApi.

#### Describe the solution you'd like
I suggest a new Input in component to "Ignore filtered list method" (i called "ignoreFilter"

#### Additional context
I cloned your repository and create this feature in another branch called "feature/ignore-filter". Can you give me a permission to send a Pull Request to you review my code? Thanks.

See u soon 😄

**Comment by atilamsantos** [comment]
up

**Comment by gmerabishvili** [comment]
Hello @mncorreialive yes, sure : ) Thank you.

**Comment by mncorreialive** [comment]
Hello! I was send a pull request with changes. Thanks!!!

**Comment by cxspxr** [comment]
@gmerabishvili any plans to merge that PR?

**Comment by gmerabishvili** [comment]
Hello, the feature is implemented. Please upgrade to latest 2.0.5 version. Thank you.
