### ISSUE TITLE
Input focus stops working if data is null or empty

### ISSUE THREAD

**Issue by Ne4istb** [gmerabishvili/angular-ng-autocomplete#13]
Reproduction:
1. Add inputFocused handler.
2. Set data to []
3. Focus input. inputFocused executed
4. Click outside.
5. Focus input. inputFocused is not executed. 

Expected: focus handler to be executed every time input is focused.

According to source 
https://github.com/gmerabishvili/angular-ng-autocomplete/blob/master/projects/autocomplete-lib/src/lib/autocomplete/autocomplete.component.ts#L449
isFocused is reset only in one place - handleClose. But if data is null, there is nothing to close and component is staying "focussed".

**Comment by Ne4istb** [comment]
Demo base on official example:
https://stackblitz.com/edit/angular-ng-autocomplete-ckhthx

**Comment by gmerabishvili** [comment]
Hello, thanks for the report. The issue is resolved. Please update to latest 1.1.13 version. Thank you!

**Comment by Ne4istb** [comment]
@gmerabishvili Thanks! Good job!
