### ISSUE TITLE
border-radius css not working

### ISSUE THREAD

**Issue by trovend** [gmerabishvili/angular-ng-autocomplete#133]
we wanted a rounded text box. 
tried  with below code but its not working

.ng-autocomplete {
  width: 100% !important;
  border-radius: 25px;
}

**Comment by trovend** [comment]
also if possible do let us know how to add search icon

**Comment by gmerabishvili** [comment]
@trovend Please refer to #68  and #69 . Thank you.

**Comment by trovend** [comment]
great. thank you

**Comment by trovend** [comment]
#68  worked
