### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by cmrock** [gmerabishvili/angular-ng-autocomplete#135]
According to feature list, it states accessibility. 

But there is no voice over control on the input field.

It always says empty field. It should say label name or it should attach to <label > tag. So that it can speak loud for accessibility.

**Comment by romankuchera** [comment]
@cmrock how you fix it?

**Comment by cmrock** [comment]
@romankuchera

> @cmrock how you fix it?

 There is no solution for this till now.

**Comment by gmerabishvili** [comment]
@cmrock @romankuchera  Resolved, please upgrade to latest 2.0.6 version. Thank you!
