### ISSUE TITLE
Make Auto-Complete Required on form submit

### ISSUE THREAD

**Issue by ABMBAD8** [gmerabishvili/angular-ng-autocomplete#136]
I tried using the angular-ng-autocomplete, everything else works perfectly but when I try to make the input field to be 'required' nothing happens. The form can be submitted even though the input is empty.
Is there a way to add that as in like normal text input

**Comment by gmerabishvili** [comment]
@ABMBAD8 hey, It actually works like a normal input. I think you're doing something wrong with your implementation.  Check this for more details: https://stackblitz.com/edit/angular-ng-autocomplete-with-forms

**Comment by ABMBAD8** [comment]
Thank you @gmerabishvili, I looked at the example but it doesn't really give me the direction I was to take on my case.
I have styling which I have set on the .css file. The styling should show when a value has been selected. The styling is to change the input field color.
My problem is the input field is only rendered at runtime

**Comment by gmerabishvili** [comment]
@ABMBAD8 Can you provide your example on Stackblitz please?

**Comment by ABMBAD8** [comment]
I have created an example project: [https://stackblitz.com/edit/angular-ng-autocomplete-with-forms-bs2z5y?file=src%2Fstyles.css](https://stackblitz.com/edit/angular-ng-autocomplete-with-forms-bs2z5y?file=src%2Fstyles.css)
The style I am trying to render is in the styles.css file
The "required style does not work. When an option is selected, the input border-color should change to the color specified on line  35.

**Comment by gmerabishvili** [comment]
@ABMBAD8  Generally "required" on input doesn't work like that when using reactive forms. Check how validation works on Reactive forms.

**Comment by ABMBAD8** [comment]
Isn't there a way besides using Reactive forms? I have a huge project that is running already and changing it to reactive forms might ruin the project or take a lot to change

**Comment by gmerabishvili** [comment]
@ABMBAD8 I'm not telling you to change it to reactive forms. I thought you were already using Reactive forms , because you have `formControlName` in your Stackblitz example. But anyway, to make the validations work, you need to use Reactive or template driven forms.

**Comment by daniloak** [comment]
Hi I ended up having the same issue, but it seems it only happens when we use FormGroup instead FormBuilder.
The form is always valid
https://stackblitz.com/edit/angular-ng-autocomplete-with-forms-an42gu?file=src%2Fapp%2Fapp.component.ts
