### ISSUE TITLE
scrolledToEnd event fires together with closed event

### ISSUE THREAD

**Issue by mstankovic2903** [gmerabishvili/angular-ng-autocomplete#137]
#### Expected result
scrolledToEnd should fire only when a user scrolls to the end of the drop down list.

#### Actual result
Currently, the scrolledToEnd is fired when a user scrolls to the end (that's fine and expected), but it's also fired when a user scrolls a little bit (not to the end) and then clicks outside the autocomplete list. The list closes, and the scrolledToEnd event fires (this behaviour is not expected).

#### Steps to reproduce

1. Enter some search criteria which produces lots of results and scroll appears.
2. Scroll little bit, but not to the end.
3. Click outside the result list.
4. `scrolledToEnd` fires together with `closed` event
#### Context

Let's say that the data is fetch from a server in pages. If the `scrolledToEnd` event is used to increment the current page and fetch it from the server, a new unnecessary request will be made on closing the list. If a user enter some criteria and keeps repeating the steps 2 and 3 from above, a new page will be fetched each time and the result list will get longer.

I checked the code and saw what makes the problem. I suggests to change the `scrollToEnd` method in the following way. When the list is closed `elementHeight` is `0` and also `atBottom` becomes `true`. Maybe `atBottom` should be calculated in the following way: 
```js
const atBottom = elementHeight !=0 && scrollHeight === scrollTop + elementHeight;
```

#### Your Environment

* Version used: 2.0.5

**Comment by gmerabishvili** [comment]
@mstankovic2903  Resolved, please upgrade to latest 2.0.6 version. Thank you!
