### ISSUE TITLE
Not able to get Input value if data is not available

### ISSUE THREAD

**Issue by sanket29395** [gmerabishvili/angular-ng-autocomplete#14]
I am trying to get input value if the value is not available in data.

Please help me to solve this problem...

**Comment by gmerabishvili** [comment]
Hello, can you provide more details or an example please?

**Comment by sanket29395** [comment]
For example , I have
   data = [
     {
       id: 1,
       name: 'Usa'
     },
     {
       id: 2,
       name: 'England'
     }
  ]

and someone try to search "India" then I am not able to get input search "India" on click enter.

I temporary used onChangeSearch function to store in variable but if there is a different function then I would like to implement in my code.

**Comment by gmerabishvili** [comment]
You use onChangeSearch function correctly. Keep using it. There's no any different implementation for that case at this moment. Thank you.
