### ISSUE TITLE
Unable to install the library on Angular 11 - potentially incorrect tslib dependency version

### ISSUE THREAD

**Issue by mmanista** [gmerabishvili/angular-ng-autocomplete#141]
I've seen a similar issue that's already been reported, but there was no solution provided, so wondering if this should actually get fixed or is there a different workaround

Unable to install the library on Angular 11 - there are different versions of `tslib` that are conflicting (`2.0.0` in local project, needed in Angular 10+ and `1.x.x` in the library)

```npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: xxxxx
npm ERR! Found: tslib@2.0.0
npm ERR! node_modules/tslib
npm ERR!   tslib@"2.0.0" from the root project
npm ERR!   tslib@"^2.0.0" from @angular/common@11.0.9
npm ERR!   node_modules/@angular/common
npm ERR!     @angular/common@"~11.0.0" from the root project
npm ERR!     peer @angular/common@"*" from angular-ng-autocomplete@2.0.5
npm ERR!     node_modules/angular-ng-autocomplete
npm ERR!       angular-ng-autocomplete@"*" from the root project
npm ERR!   1 more (@angular/core)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer tslib@"^1.10.0" from angular-ng-autocomplete@2.0.5
npm ERR! node_modules/angular-ng-autocomplete
npm ERR!   angular-ng-autocomplete@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

#### Expected result
The package should be installing properly

#### Actual result
`npm install` errors out, so I'm unable to use the library

#### Steps to reproduce
1. Create a new Angular project `~11.0.0`
2. See what's your `tslib` version in `package.json` - it should be `2.x.x`
3. `npm install angular-ng-autocomplete --save`
4. check if it succeed or not

Angular has posted a little document about necessary `tslib` migration in the libraries - that might be useful: https://angular.io/guide/migration-update-libraries-tslib

* Version used: latest (2.0.5)
* Browser Name and version: n/a
* Operating System and version: macOS Mojave

Thanks in advance for any feedback!

**Comment by gmerabishvili** [comment]
@mmanista  Here is the working example in Angular 11. https://stackblitz.com/edit/angular-ng-autocomplete-with-forms-test?file=package.json.   Maybe there's some problem in your project?

**Comment by mmanista** [comment]
@gmerabishvili thanks for the reply. There must be something else missing/different in my project that causes this issue, but unfortunately I couldn't figured it out, so ended up using a different autocomplete library.
Thanks for the support!
