### ISSUE TITLE
Setting initialValue to a function that returns a default value, is calling the function infinitely

### ISSUE THREAD

**Issue by nupurkamble904** [gmerabishvili/angular-ng-autocomplete#143]
#### Bug description

I'm trying to call a function to set the initial value. This function returns the default value that needs to be set. But this function is being called continuously and as this is setting the initial value, the function on selected(event) is also being called each time.

#### Steps to reproduce

html file

`<ng-autocomplete [placeholder]="'Please select an option'" id="name" name="name" [initialValue]="getVal()" selected)='selectOption($event)' [data]="data" [searchKeyword]="'name'" [itemTemplate]="itemTemplate [notFoundTemplate]="notFoundTemplate"></ng-autocomplete>`

ts file 

`getVal(){ return { "id":"1",  "name":"test" } }`

#### Context

Instead of a basic getValue function I am actually trying to dynamically set the initialValue depending on some code being run. But this simple function gives the same issue.

#### Your Environment
I'm using Angular 8.

**Comment by gmerabishvili** [comment]
Angular uses changeDetection lifecycle multiple times to check if the function has changed for [class.selected] or ngClass etc. If you use function, it will call multiple times. For this reason the use of function is not advised when you bind, instead you should get the initial value in your `component.ts` file and just bind the value  to ` [initialValue]`.
