### ISSUE TITLE
Using inside table

### ISSUE THREAD

**Issue by StevRoger** [gmerabishvili/angular-ng-autocomplete#144]
#### Bug description
Cannot use inside table

#### Expected result
Able to select within the table row

#### Actual result
The selection options was hidden behind the table

#### Steps to reproduce

1. Install Angular Autocomplete in Angular 8 project
2. Import to module and use inside table
3. Cannot select the select options
#### Your Environment
Angular 8
Windows 10 x64

* Version used: Lastest
* Browser Name and version:
* Operating System and version:
* Link to your project:

**Comment by gmerabishvili** [comment]
I'm closing it for now, because it needs further clarification.
