### ISSUE TITLE
multiple(different) autocompletes on one page

### ISSUE THREAD

**Issue by YouNone** [gmerabishvili/angular-ng-autocomplete#146]
I have a problem with displaying multiple autocompletes.
When I enter information in the second autocomplete, it is not displayed in it, but if I hover over the first autocomplete I see results for the second.
Autocompletes have different input data, but the link to the container is the same.
snippet of code:
      <div class="text1">I want to hear from
        <div class="ng-autocomplete">
          <ng-autocomplete
            placeholder="your target audience"
            [data]="target_group_suggestions"
            [searchKeyword]="target_group"
            (inputChanged)='onChangeSearch($event, "tg")'
            [itemTemplate]="itemTemplate"
            [customFilter]="customFilter"
            [notFoundTemplate]="notFoundTemplate">
          </ng-autocomplete>
          <ng-template #itemTemplate let-item>
          <a [innerHTML]="item"></a>
          </ng-template>
          <ng-template #notFoundTemplate let-notFound></ng-template>
          </div>
      </div>
      <div class="text1">
        about insights on
        <div class="ng-autocomplete">
          <ng-autocomplete
            placeholder="a topic"
            [data]="insight_suggestions"
            [searchKeyword]="insight"
            (inputChanged)='onChangeSearch($event, "ins")'
            [itemTemplate]="itemTemplate"
            [customFilter]="customFilter"
            [notFoundTemplate]="notFoundTemplate"
            (focusout)="clearSuggestion($event)"
            >
          </ng-autocomplete>
          <ng-template #itemTemplate let-item>
          <a [innerHTML]="item"></a>
          </ng-template>
          <ng-template #notFoundTemplate let-notFound></ng-template>
        </div>
      </div>

**Comment by gmerabishvili** [comment]
@YouNone  Please refer here #23  Also re-check the examples on Doc page.

**Comment by YouNone** [comment]
@gmerabishvili I have a different situation, the results of the second autocomplete appear in the field of the first autocomplete.

**Comment by gmerabishvili** [comment]
@YouNone  Can you share your implementation in Stackblitz? I think you're doing something wrong.

**Comment by YouNone** [comment]
https://stackblitz.com/edit/angular-ivy-hr6z9e?file=src%2Fapp%2Fapp.component.html
just html and ts

**Comment by YouNone** [comment]
@gmerabishvili Are there any updates on the issue?

**Comment by gmerabishvili** [comment]
@YouNone  Unfortunately, I didn't have time to go through in details. Did you fix the problem BTW?

**Comment by vkyadav03** [comment]
I was facing the same issue but now it is resolved...
just need to put [itemTemplate] with a different name and also [searchKeyword] with different name ex..
first : ng-autocomplete > [itemTemplate]="firstItemTemplate"
second : ng-autocomplete > [itemTemplate]="SecondItemTemplate"

![image](https://user-images.githubusercontent.com/31218461/114821455-39071c80-9dde-11eb-964e-25b4d1e9176a.png)

**Comment by vkyadav03** [comment]
@YouNone can you look that my previous message, it is working for you or not?
