### ISSUE TITLE
changeDetection: ChangeDetectionStrategy.OnPush issue

### ISSUE THREAD

**Issue by friksa** [gmerabishvili/angular-ng-autocomplete#155]
#### Bug description

Autocomplete is delayed by exactly one character when showing suggestions and using it with:
```
changeDetection: ChangeDetectionStrategy.OnPush,
```

#### Expected result
Each keypress should immediately update the suggestions instead of waiting for the next keypress.

#### Workaround
This code change in the component resolves the issue:
```
changeDetection: ChangeDetectionStrategy.Default,
```

#### Your Environment
Angular 11

* Version used: latest
* Browser Name and version: Chrome
* Operating System and version: Mac

For performance reasons, it would be nice to support OnPush change detection.

**Comment by gmerabishvili** [comment]
@friksa  Hello, can you provide a Stackblitz example please?

**Comment by gmerabishvili** [comment]
@friksa  That's correct change detection behavior.  You are not supposed to use ChangeDetectionStrategy.OnPush on "containers" components. But it's ideal for components that only have inputs/outputs - but do not have their own internal state. But anyway, if you use ChangeDetectionStrategy.OnPush in your component you can call this.cd.markForCheck(); inside http call subscription after you receive new data.
