### ISSUE TITLE
Filtering list does not work when data is previously mapped

### ISSUE THREAD

**Issue by tdysko** [gmerabishvili/angular-ng-autocomplete#156]
Filtering list does not work when data is previously mapped

Is there any reason why the item.constructor === Object is performed?

`
filterList() {
        this.selectedIdx = -1;
        this.initSearchHistory();
        if (this.query != null && this.data) {
            this.toHighlight = this.query;
            this.filteredList = this.data.filter((/**
             * @param {?} item
             * @return {?}
             */
            (item) => {
                if (typeof item === 'string') {
                    // string logic, check equality of strings
                    return item.toLowerCase().indexOf(this.query.toLowerCase()) > -1;
                }
                else if (typeof item === 'object' && item.constructor === Object) {
                    // object logic, check property equality
                    return item[this.searchKeyword].toLowerCase().indexOf(this.query.toLowerCase()) > -1;
                }
            }));
        }
        else {
            this.notFound = false;
        }
    }
`

I'm trying to populate the datasource this way:

`
this.service.loadProducts()
      .pipe(
        map(response => response.map(element => { return new Product(element) }))
      )
      .subscribe(arr => {
        this.products = arr;
      });
`

but the object does not contain a constructor hence the else-if expression fails.

* Version used:
Angular 11

**Comment by gmerabishvili** [comment]
@tdysko   Can you provide a Stackblitz example please?

**Comment by gmerabishvili** [comment]
Due to insufficient information I'm closing this issue for now.
