### ISSUE TITLE
Is there anyway to group item in list?

### ISSUE THREAD

**Issue by smkamranqadri** [gmerabishvili/angular-ng-autocomplete#162]
I want to show item in list with group which I don't see any guide? like in below screenshot?

![segmented drop-down results example](https://user-images.githubusercontent.com/13115396/127750801-0fcd13d7-cdd0-4690-baee-98b65b1177cb.png)

**Comment by gmerabishvili** [comment]
@smkamranqadri  Unfortunately the library doesn't support that feature.
