### ISSUE TITLE
On autocomplete textbox click data list Is not populate.

### ISSUE THREAD

**Issue by Sagar4412** [gmerabishvili/angular-ng-autocomplete#165]
Recently I've upgraded my angular application from version 8.2 to 9.1 and I've used angular-ng-autocomplete package In my application.
Now the problem Is when I'm clicking on textbox data are not populate In list and when I'm typing anything In textbox it will show the result and after that, it will work as usual. The main problem Is when it load first time data is not populate on the textbox click.

Data list should be open on the textbox click

Data list Is not populate In list when application load first time.

#### Steps to reproduce

**Code**
                     `<div class="ng-autocomplete">
                        <ng-autocomplete [placeholder]="'Vehicle Make'" [data]="makeList" 
                          [(ngModel)]="selectedMakelist.VehicleMake" [ngModelOptions]="{standalone: true}" [searchKeyword]="keyword" 
                          (selected)='selectEvent($event)' [itemTemplate]="itemTemplate" [notFoundTemplate]="notFoundTemplate">
                        </ng-autocomplete>
                        <ng-template #itemTemplate let-item>
                          <a [innerHTML]="item.VehicleMake | safeHtml"></a>
                        </ng-template>
                        <ng-template #notFoundTemplate let-notFound>
                          <div [innerHTML]="notFound | safeHtml"></div>
                        </ng-template>
                      </div>`
**Package.json**
`"dependencies": {
    "@angular-slider/ngx-slider": "^2.0.3",
    "@angular/animations": "~9.1.13",
    "@angular/cdk": "^9.2.4",
    "@angular/common": "~9.1.13",
    "@angular/compiler": "~9.1.13",
    "@angular/core": "~9.1.13",
    "@angular/forms": "~9.1.13",
    "@angular/localize": "^9.1.13",
    "@angular/material": "^9.2.4",
    "@angular/material-moment-adapter": "^9.2.4",
    "@angular/platform-browser": "~9.1.13",
    "@angular/platform-browser-dynamic": "~9.1.13",
    "@angular/platform-server": "~9.1.13",
    "@angular/router": "~9.1.13",
    "@fortawesome/angular-fontawesome": "^0.9.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.35",
    "@fortawesome/free-brands-svg-icons": "^5.15.3",
    "@fortawesome/free-solid-svg-icons": "^5.15.3",
    "@ng-bootstrap/ng-bootstrap": "^6.2.0",
    "@ng-toolkit/universal": "^8.1.0",
    "@nguniversal/express-engine": "^9.1.1",
    "@types/jquery": "^3.5.6",
    "angular-instantsearch": "^2.3.0",
    "angular-ng-autocomplete": "^2.0.5",
    "core-js": "^2.6.12",
    "domino": "^2.1.6",
    "express": "^4.15.2",
    "fs": "0.0.1-security",
    "gulp": "^4.0.2",
    "jquery": "^3.6.0",
    "lottie-web": "^5.7.12",
    "moment": "^2.29.1",
    "n": "^6.8.0",
    "ng-intercom": "^8.0.2",
    "ng-lazyload-image": "^7.1.0",
    "ng2-search-filter": "^0.5.1",
    "ng2-validation": "^4.2.0",
    "ngx-cookie-service": "^2.4.0",
    "ngx-currency": "^2.5.2",
    "ngx-device-detector": "^1.5.2",
    "ngx-extended-pdf-viewer": "0.9.35",
    "ngx-lottie": "^7.0.3",
    "ngx-mask": "^8.2.0",
    "ngx-owl-carousel-o": "^3.1.1",
    "ngx-sharebuttons": "^8.0.5",
    "ngx-toastr": "^14.0.0",
    "node-cache": "^5.1.2",
    "node-sass": "^4.14.1",
    "rxjs": "~6.5.4",
    "rxjs-compat": "6.3.3",
    "sweetalert2": "^8.19.0",
    "tslib": "^1.10.0",
    "validator": "^11.1.0",
    "zone.js": "~0.10.2"
  },`

#### Your Environment

* Angular version: 9.1
* Version used: 2.0.5
* Browser Name and version: Google Chrome and Version 86.0.4240.111
* Operating System and version: Linux and version 18
* Link to your project:

**Comment by donthisai** [comment]
I also have the same issue and on-click in text field will not show the data list unless I type something or click away on any document and again click on text field. 

I am using angular version 11.0.2

_package.json_

{
  "name": "My product",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod --aot --vendor-chunk --common-chunk --delete-output-path --build-optimizer",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "postinstall": "ngcc --properties es5 browser module main --first-only"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^11.0.2",
    "@angular/common": "~11.0.2",
    "@angular/compiler": "~11.0.2",
    "@angular/core": "~11.0.2",
    "@angular/forms": "~11.0.2",
    "@angular/localize": "~11.0.2",
    "@angular/platform-browser": "~11.0.2",
    "@angular/platform-browser-dynamic": "~11.0.2",
    "@angular/router": "~11.0.2",
    "@ng-bootstrap/ng-bootstrap": "^8.0.0",
    "angular-ng-autocomplete": "^2.0.5",
    "apexcharts": "^3.25.0",
    "bootstrap": "^5.0.0-alpha1",
    "crypto-js": "^3.1.8",
    "flatpickr": "^4.6.9",
    "font-awesome": "^4.7.0",
    "ng-apexcharts": "^1.5.6",
    "ng-multiselect-dropdown": "^0.3.4",
    "ng2-flatpickr": "^9.0.0",
    "ngx-order-pipe": "^2.1.1",
    "ngx-treeview": "^10.0.2",
    "rxjs": "~6.5.5",
    "subsink": "^1.0.2",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1100.2",
    "@angular/cli": "^11.2.3",
    "@angular/compiler-cli": "~11.0.2",
    "@types/crypto-js": "^4.0.2",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/lodash": "^4.14.172",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.1.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "style-loader": "^1.2.1",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.5",
    "webpack": "^4.44.1"
  }
}

---------------------------------

_My code for autocomplete.html is as below_
*******************************
<div class="ng-autocomplete" style="z-index: 999;">
    <ng-autocomplete
        #autoComplete
        [data]="data" [searchKeyword]="keyword" (selected)='selectEvent($event)'
        (inputChanged)='onChangeSearch($event)' (inputFocused)='onFocused($event)' [itemTemplate]="itemTemplate"
        [notFoundTemplate]="notFoundTemplate"
        minquerylength="1"
        placeholder= "Search.."
    >
    </ng-autocomplete>

    <ng-template #itemTemplate let-item>
        <a href="javascript:void(0)">
            <span [innerHTML]="item.icon"></span>
            <span [innerHTML]="item.name"></span>
        </a>
    </ng-template>

    <ng-template #notFoundTemplate let-notFound>
        <div>No records found</div>
    </ng-template>
</div>
*******************************

**Comment by gmerabishvili** [comment]
@Sagar4412  @donthisai  Versioning has nothing to do with this issue.  I think the issue can be how you initialize data when you pass it to autocomplete.

**Comment by Sagar4412** [comment]
@gmerabishvili Data passing flow Is the same as it is. Please have a look at following
HTML
`<ng-autocomplete [placeholder]="'Type your car make'" [data]="makeList"
                      [(ngModel)]="selectedMakelist.VehicleMake" [ngModelOptions]="{standalone: true}"
                      [searchKeyword]="keyword" (selected)='selectEvent($event)' [itemTemplate]="itemTemplate"
                      [notFoundTemplate]="notFoundTemplate"></ng-autocomplete>
                    <ng-template #itemTemplate let-item>
                      <a [innerHTML]="item.VehicleMake | safeHtml"></a>
                    </ng-template>
                    <ng-template #notFoundTemplate let-notFound>
                      <div [innerHTML]="notFound | safeHtml"></div>
                    </ng-template>`
ts
`  getMakeList() {
    this.pinkelephantService.getMakeList().subscribe(resp => {
      if (resp) {
        this.makeList = resp;
      }
    });
  }`
 And this getMakeList() function Is called In constructor.

**Comment by gmerabishvili** [comment]
@Sagar4412  Do you still face that issue?
