### ISSUE TITLE
Open Panel

### ISSUE THREAD

**Issue by Golldden** [gmerabishvili/angular-ng-autocomplete#167]
How to keep the panel opened even after clicking on an item?

**Comment by gmerabishvili** [comment]
@Golldden  Currently the library doesn't support feature like that, but try call `open()` method on `(selected)` event. Check docs for further details. Thank you.

**Comment by Golldden** [comment]
Thank you very much , the library is great and helpful

**Comment by gmerabishvili** [comment]
@Golldden  Thank you!
