### ISSUE TITLE
ng-autocomplete displaying '[object Object]' 

### ISSUE THREAD

**Issue by jesus-20** [gmerabishvili/angular-ng-autocomplete#170]
TS Code:
`public TitleSelected: BaseEntity;`
...
`
   this.TitleSelected= {id: this.model.titleId, title: this.model.title};
`
HTML Code: 
`
  <ng-autocomplete  [(ngModel)]="TitleSelected" [data]="titles" [searchKeyword]="keyword"
                  (inputChanged)='onChangeSearchTitle($event)' notFoundText="موردی
                  یافت نشد" [notFoundTemplate]="notFoundTemplate" [isLoading]="loadingTitleList" [minQueryLength]="0"
                  [itemTemplate]="itemTemplate" heading="لیست عنوان های موجود در سیستم"
                  historyIdentifier="Title_Titles_History" [historyHeading]="historyHeading" historyListMaxNumber="10"
                  placeHolder="عنوان محصول">
  </ng-autocomplete>
`

`[initialValue] ` is not work

**Comment by gmerabishvili** [comment]
Did you fix this issue?

**Comment by gmerabishvili** [comment]
Due to insufficient information I'm closing this issue for now.
