### ISSUE TITLE
Remove automatic dependency on fonts.google.com

### ISSUE THREAD

**Issue by auclemi** [gmerabishvili/angular-ng-autocomplete#173]
The company I am working for has a policy which does not allow the developers to have external dependencies at runtime. This way I cannot use the angular-ng-autocomplete since it fetches some CSS to fonts.gooogleapis.com
Could it be possible to put this as an optional parameter ?

**Comment by gmerabishvili** [comment]
@auclemi  Resolved, please upgrade to latest 2.0.6 version. Thank you!

**Comment by mrkhan** [comment]
Could someone explain me, how is it resolved? We have this same issue, and we are using v2.0.12 and have observed that it makes external request to fonts.googleapis.com
