### ISSUE TITLE
angular 11 support

### ISSUE THREAD

**Issue by shaiis1** [gmerabishvili/angular-ng-autocomplete#174]
Hi @gmerabishvili ,

I've used you're example on angular 11 and the auto complete isn't working.

is the lib support angular 11? if does, I would like to get some help.

Thanks!

**Comment by gmerabishvili** [comment]
@shaiis1  Hi, yes the library supports Angular 11 and above.

**Comment by gmerabishvili** [comment]
@shaiis1 New version coming soon...

**Comment by gmerabishvili** [comment]
@shaiis1  Resolved, please upgrade to latest 2.0.6 version. Thank you!
