### ISSUE TITLE
list ng-packgr and core-js as devDependencies

### ISSUE THREAD

**Issue by almarro1** [gmerabishvili/angular-ng-autocomplete#176]
When installing on newer angular versions, there is conflict in the used version of tslib (1.10.0 vs 2.3.0). 
#### Bug description
This is because in "dependencies" both ng-packagr and core-js are included. These two should be moved to devDependencies

#### Expected result
Installing with angular 13 should not fail due to unresolved version on tslib

**Comment by gmerabishvili** [comment]
@almarro1  New version coming soon...

**Comment by gmerabishvili** [comment]
@almarro1 Resolved, please upgrade to latest 2.0.6 version. Thank you!
