### ISSUE TITLE
How set custom css for autocomplete input?

### ISSUE THREAD

**Issue by rashedshaon** [gmerabishvili/angular-ng-autocomplete#18]
I am trying to set css for autocomplete  height and auto suggestion list z-index but they are not working. I am like bellow,

```
.autocomplete-container .input-container input {
  font-size: 14px;
  padding: 0 6px;
  height: 25px;
}
.autocomplete-container .suggestions-container {
  z-index: 9999;
}
```

**Comment by gmerabishvili** [comment]
Hello, use /deep/ combinator like this:
/deep/ .autocomplete-container .input-container input {
  font-size: 14px;
  padding: 0 6px;
  height: 25px;
}

**Comment by teodoramalec** [comment]
@gmerabishvili 
I have tried this, but won't work, i have tried with ng-autocomplete
How can I change this?

.autocomplete-container .suggestions-container ul li.item a {
    background-color: white !important;
    color: black !important;
}

**Comment by gmerabishvili** [comment]
@teodoramalec /deep/ is deprecated after Angular 8. Use ::ng-deep instead. Thank you!
