### ISSUE TITLE
Build issue for versions ^2.0.5

### ISSUE THREAD

**Issue by debadatta-tiger-analytics** [gmerabishvili/angular-ng-autocomplete#184]
#### static ɵfac: i0.ɵɵFactoryDeclaration<AutocompleteComponent, never>;

node_modules/angular-ng-autocomplete/lib/autocomplete-lib.module.d.ts:7:21 - error TS2694: Namespace '"D:/Projects/cbulvl/MARS/frontend/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mars@1.1.0 build: `ng build --prod`
npm ERR! Exit status 1

#### Steps to reproduce

1. ng build --prod
#### Your Environment

* Version used: 10
* Browser Name and version: Chrome
* Operating System and version: Windows 10

**Comment by gmerabishvili** [comment]
@debadatta-tiger-analytics  Please upgrade to latest version. Thank you

**Comment by debadatta-tiger-analytics** [comment]
@gmerabishvili I have tried with the updated versions as well. It fails while building.

**Comment by gmerabishvili** [comment]
@debadatta-tiger-analytics  What version of Angular are you using?

**Comment by debadatta-tiger-analytics** [comment]
Angular 10 @gmerabishvili

**Comment by gmerabishvili** [comment]
@debadatta-tiger-analytics  try 2.0.6 or 2.0.7  it will work.

**Comment by debadatta-tiger-analytics** [comment]
@gmerabishvili sure. Let me check with the aforementioned versions.

**Comment by gmerabishvili** [comment]
@debadatta-tiger-analytics  Did it work?

**Comment by debadatta-tiger-analytics** [comment]
Thank you @gmerabishvili. version 2.0.7 and reinstalling node modules after deleting everything worked.
