### ISSUE TITLE
reset value of [(ngModel)]  is not updating in html view (angular 7)

### ISSUE THREAD

**Issue by Dhamu143** [gmerabishvili/angular-ng-autocomplete#19]
I am using angular 7 and want to reset [(ngModel)] value but its not update the view by null or '' . 

<ng-autocomplete
    [data]="countries"
    [searchKeyword]="keyword"
    placeHolder="Enter the Country Name"
    (selected)='selectEvent($event)'
    (inputChanged)='onChangeSearch($event)'
    (inputFocused)='onFocused($event)'
    historyIdentifier="countries"
   [(ngModel)]="selected.Country"
    [itemTemplate]="itemTemplate"
    [notFoundTemplate]="notFoundTemplate">
  </ng-autocomplete>

if once we assign some value to selected.Country then if we assign/reset to null or empty it not reflect to view.

**Comment by gmerabishvili** [comment]
Hello, can you provide an example in Stackblitz?

**Comment by Dhamu143** [comment]
check it here 

https://stackblitz.com/edit/angular-uynmnv

after select value click on reset button it will not reset value to html.

**Comment by gmerabishvili** [comment]
Hello, The issue is resolved. Please update to latest 1.1.14 version. Thank you!

**Comment by Dhamu143** [comment]
Please provide some more information or update your read me or content.
