### ISSUE TITLE
Material Icons in angular universal

### ISSUE THREAD

**Issue by Ali-omidian** [gmerabishvili/angular-ng-autocomplete#198]
#### Your Environment

* Version used: ^2.0.8
* Browser Name and version: chrome
* Operating System and version: windows
* Link to your project:

**Comment by gmerabishvili** [comment]
@Ali-omidian Ok, thank you for report. Use version 2.0.5 for now.

**Comment by Ali-omidian** [comment]
in version 2.0.9 that bug has been reolved?

**Comment by gmerabishvili** [comment]
@Ali-omidian  Yes, it has been resolved.
