### ISSUE TITLE
Trouble when build

### ISSUE THREAD

**Issue by willwalker** [gmerabishvili/angular-ng-autocomplete#2]
I am using Angular CLI 7.1.4. When i build, get this error:

ERROR in ./node_modules/angular-ng-autocomplete/autocomplete-lib.ngfactory.js
Module not found: Error: Can't resolve 'autocomplete-lib'

How can i fix it?

Thanks!

**Comment by gmerabishvili** [comment]
Hello, thanks for the report. The issue is resolved. Please update to latest 1.0.5 version and let me know if everything is OK. Thank you!
