### ISSUE TITLE
How to set default value for the input.?

### ISSUE THREAD

**Issue by VigneshSAN** [gmerabishvili/angular-ng-autocomplete#21]
Hi,

How can I set the default value for the input. Even I tried using the initialValue parameter but nothing works. Kindly help me regarding this issue as soon as possible.

Thanks & regards,
Vignesh Mohanraj

**Comment by gmerabishvili** [comment]
Hello, I think you're doing something wrong. "initialValue" works nicely. You can make it work like this:
ts:
initialVal={
      id: 1,
      name: 'Georgia',
    },
template:
[initialValue]="initialVal"

Thank you.

**Comment by sergiofsu1bank** [comment]
Hi @gmerabishvil, I have a simular problem. Can you help me? 

I try to do a cities autoComplete with API data, but I shuld to return "id" not "city".

My Component.ts

keyword = 'cidade';
keywords = ['pais', 'sigla', 'cidade'];

  listPlaces() {
    this.service.getCities().subscribe((data) => {
      this.palce = (data.data as PlaceModel[]).filter((func) => func);
    });
  }

My HTML

            <select [(ngModel)]="keyword" [ngModelOptions]="{standalone: true}">
              <option *ngFor="let item of keywords" [value]="item">{{ item }}</option>
            </select>

            <div>
              <ng-autocomplete
                (click)="listPlaces()"
                formControlName="idSrc"
                [data]="place"
                [searchKeyword]="keyword"
                placeholder="Cities"
                historyIdentifier="city"
                [itemTemplate]="itemTemplate"
                [notFoundTemplate]="notFoundTemplate">
              </ng-autocomplete>

              <ng-template #itemTemplate let-item>
                <span [innerHTML]="item.city"></span> &nbsp; | &nbsp;
                <span [innerHTML]="item.country"  ></span>
              </ng-template>

              <ng-template #notFoundTemplate let-notFound>
                <div [innerHTML]="notFound"></div>
              </ng-template>
            </div>

**Comment by gmerabishvili** [comment]
@sergiofsu1bank  Please, check the docs. Thank you.

**Comment by Mark-Hetherington** [comment]
Is there further documentation beyond the readme.md? 

I'm trying to use a formControlName that targets a numeric ID in the form, and presently the value is being set to an entire data object. I suppose one has to use the (selected) output instead to update the form value?

**Comment by gmerabishvili** [comment]
@Mark-Hetherington  Hello, no readme.md is the only documentation for now. If you use forms you can set default value by setValue or patchValue. It will work.
