### ISSUE TITLE
Package needs a license

### ISSUE THREAD

**Issue by Amos47** [gmerabishvili/angular-ng-autocomplete#22]
I was hoping to make use of this package, but without a license, it would be illegal for me to use in a for profit project.

If you want to allow companies to make use of the tool, I'd suggest MIT or BSD style license.
It removes any ambiguity.

If you want to force it to be open sourced in perpetuity, you can use a GPL style license.

**Comment by gmerabishvili** [comment]
Hello thanks for your advice. I finally added a MIT style license. Please update to latest 1.1.14 version. Thank you and good luck!
