### ISSUE TITLE
IE/Edge Close(x) icon duplicate 

### ISSUE THREAD

**Issue by MehdiM62** [gmerabishvili/angular-ng-autocomplete#24]
Within IE and Edge browser there is a case that close icon (x) will be doubled per blow screenshot.  

![image](https://user-images.githubusercontent.com/19629619/61615386-7afe3f80-ac98-11e9-8933-c8e45eb09e95.png)

Step to reproduce:
1- select and item form the component.
2- click on the component again.

Thanks in advance.

**Comment by gmerabishvili** [comment]
Hello, The issue is resolved. Please update to latest 1.1.14 version. Thank you!
