### ISSUE TITLE
isLoading isn't working properly

### ISSUE THREAD

**Issue by beevk** [gmerabishvili/angular-ng-autocomplete#25]
If `isLoading` is set (doesn't matter `true` of `false`), the loading spinner keeps on showing. However, we can directly set `isLoading = ""` (i.e empty string) to act as if it was set to `false`.

**Comment by gmerabishvili** [comment]
Hello, can you provide an example? I just tested and I couldn't provoke that bug.

**Comment by gmerabishvili** [comment]
Hello, can you provide an example? I just tested and it works properly.

**Comment by beevk** [comment]
Please check it [here](https://stackblitz.com/edit/angular-ng-autocomplete-tjxtwi).

**Comment by gmerabishvili** [comment]
You should use brackets if you have your variable in ts file: [isLoading]="isLoading"

**Comment by beevk** [comment]
@gmerabishvili That was so silly of me. Thank you so much.
