### ISSUE TITLE
Not found

### ISSUE THREAD

**Issue by thebpmgroup** [gmerabishvili/angular-ng-autocomplete#28]
Instantiated the control and supplied a valid JSON object : 

 {taxonomy_id: "1", taxonomy: "Taxonomy 1"},{ {taxonomy_id: "2", taxonomy: "Taxonomy 2"}

From the HTML template : 

<ng-autocomplete    
                    id="taxonomy" #taxonomy
                    [data]="data"
                    [searchKeyword]="keyword"
                    (selected)='selectEvent($event)'
                    (inputChanged)='onChangeSearch($event)'
                    (inputFocused)='onFocused($event)'
                    [itemTemplate]="itemTemplate"
                    [notFoundTemplate]="notFoundTemplate">                                 
                </ng-autocomplete>

Using this for onchange

onChangeSearch(val: string) {
      this.taxonomy.getAll().subscribe((result:Taxonomy[])=>{
        this.auto.data = result;
      });  
    }

The event fires ok, and without errors.

Just always fires the unfound template. Why?

**Comment by gmerabishvili** [comment]
Hello, I tested and everything works properly. I think you're doing something wrong. Could you provide an example in Stackblitz please?
