### ISSUE TITLE
How Can I add Data Dynamically ? 

### ISSUE THREAD

**Issue by santhanakrishnanstark** [gmerabishvili/angular-ng-autocomplete#29]
this.countryList.push({
      id: 13,
      name: 'Newly Added',
    });

     view.html
      <ng-autocomplete
       [data]="countryList"
       </ng-autocomplete>

   the above contryList is the array type and the data is fetch only which is in static data added in the ts file.

While i trying to add new country to country list it is added but not updated in the view of autocomplete, how can i make this visible in the view ?

**Comment by santhanakrishnanstark** [comment]
this.countryList.push({
      id: 13,
      name: 'Newly Added',
    });

While i trying to add new country to country list it is added but not updated in the view of autocomplete, how can i make this visible in the view ?

**Comment by JojiePalahang** [comment]
Hi @santhanakrishnanstark  - this is only my idea you can try if you want, hope it will help you.

Option 1
`let list = [{id: 1, name : India}];
this.countryList = this.countryList.concat(list);
`

Option 2
`let list = [{id: 1, name : India}];
this.countryList = [...this.countryList,...list];
`

**Comment by gmerabishvili** [comment]
Hello, I just tested and pushed new object in the array and it updated in the view. Could you provide an example in Stackblitz to  figure out what you're doing wrong.

**Comment by santhanakrishnanstark** [comment]
Hi @gmerabishvili and @JojiePalahang Its working fine now , I just forget something in my code thanks for your response.
