### ISSUE TITLE
Can we search after when user enter 3 to 4 characters ?

### ISSUE THREAD

**Issue by djay007** [gmerabishvili/angular-ng-autocomplete#3]
Hi , 
I want to add autocomplete only when when user enter first 3 to 4 characters and after that result should show . Can we do in that way ? I can see in documentation two methods are there 1) onChangeSearch 2)onFocused but not sure how i can achive.

**Comment by gmerabishvili** [comment]
Hello, I added "minQueryLength" input for that. Please check documentation and update to latest 1.1.7 version and let me know if everything is OK. Thank you!

**Comment by djay007** [comment]
Thanks Mate , It works !!
