### ISSUE TITLE
scrolledToEnd event not fired

### ISSUE THREAD

**Issue by amarshilpakar** [gmerabishvili/angular-ng-autocomplete#30]
(scrolledToEnd) event is not fired when I scrolled the autocomplete panel to end.

**Comment by gmerabishvili** [comment]
Hello, I just tested and it works properly. I think you're doing something wrong. Here is the working example:
html:
<div class="ng-autocomplete">
  <ng-autocomplete
    [data]="countries"
    [searchKeyword]="keyword"
    (scrolledToEnd)='scrollToBottom()'
    [itemTemplate]="itemTemplate"
    [notFoundTemplate]="notFoundTemplate">
  </ng-autocomplete>

  <ng-template #itemTemplate let-item>
    <a [innerHTML]="item.name"></a>
  </ng-template>

  <ng-template #notFoundTemplate let-notFound>
    <div [innerHTML]="notFound"></div>
  </ng-template>
</div>

ts:
  scrollToBottom(){
    console.log('scrolled-to-bottom')
  }

**Comment by amarshilpakar** [comment]
Here what I have done.
HTML: 
<div class="ng-autocomplete">
          <ng-autocomplete [data]="searchList" [searchKeyword]="keyword" placeHolder="Search here"
            (selected)='selectEvent($event)' (inputChanged)='onChangeSearch($event)' (inputFocused)='onFocused($event)' [itemTemplate]="itemTemplate" (scrolledToEnd) = "onScrolledEnd()">
          </ng-autocomplete>

          <ng-template #itemTemplate let-item>
            <a [innerHTML]="item.NAME1"></a>
          </ng-template>
        </div>

TS: 

onScrolledEnd() {
    console.log("Ok working");
  }

Not working. Am I missing something?

FYI : onScrolledEnd function is triggered when clicked outside.

**Comment by gmerabishvili** [comment]
It seems OK, It should work. I tested again and found no issue not on clicked outside also. Can you provide an stackBlitz please?

**Comment by amarshilpakar** [comment]
Can you check it

https://stackblitz.com/edit/angular-dexwka

**Comment by gmerabishvili** [comment]
onScrolledEnd function isn't triggered when clicked outside. You need to remove  "alert("ok")" in 
  selectEvent(item) {
    // do something with selected item
    alert("ok")
  }, which confuses you I think.  And as for the scrolledToEnd event it works properly. I refactored your stackBlitz where I add items in the array whenever I scrolled down to the end of the panel. Check it and let me know if everything is OK.

https://stackblitz.com/edit/angular-ja7kwz

**Comment by amarshilpakar** [comment]
I check the stackBlitz you provided, but items you add in array only appear if I reopen autocomplete. What i need is to add item immediately when you scroll down to end

**Comment by gmerabishvili** [comment]
It appears immediately.  Please check it well...

**Comment by amarshilpakar** [comment]
I checked: https://stackblitz.com/edit/angular-ja7kwz 
see screenshot I have attached. Not working

![Screenshot_2](https://user-images.githubusercontent.com/16042291/62689373-6afd9400-b9ea-11e9-8802-14577e1a4f7d.png)

**Comment by gmerabishvili** [comment]
Did you really scroll down to the end of panel? Here is my screenshot as you see "test-1" appears as soon as I scrolled down to the end.

<img width="1280" alt="Screen Shot 2019-08-08 at 12 57 21 PM" src="https://user-images.githubusercontent.com/13429992/62689637-426e9d80-b9dc-11e9-96dc-eb6c55941a87.png">

**Comment by amarshilpakar** [comment]
Yes I did scroll to end..
![Screenshot_2](https://user-images.githubusercontent.com/16042291/62690220-0f340a80-b9ec-11e9-92fe-53a8549f2f71.png)

**Comment by amarshilpakar** [comment]
did some digging and found 
var atBottom = scrollHeight === scrollTop + elementHeight;
        if (atBottom) {
            this.scrolledToEnd.emit();
            this.isScrollToEnd = true;
        }
atBottom always return false. I got 
value of  scrollHeight  = 274 and 
value of  scrollTop + elementHeight= 274 and 273.5999984741211  while debugging
because of it, scrollToEnd is not being triggered.

and When closed the autocomplete both values are 0 and atBottom is true and event is triggered.

**Comment by gmerabishvili** [comment]
It works in all cases I tested. Did you resolve it?

**Comment by gmerabishvili** [comment]
I'm closing this issue, because it is tested and works properly.

**Comment by dipaliwagh30** [comment]
> I'm closing this issue, because it is tested and works properly.

@gmerabishvili , scrolledToEnd is not working as expected in windows 10.
If you type a keyword which has only alphabets, then it doesn't fire scrollToEnd. once you enter special character and data gets filtered and you scroll till the end, then only scrollToEnd fires.

could you please check this and come with the solution.

**Comment by gmerabishvili** [comment]
@dipaliwagh30  Try version 2.0.5 for now.

**Comment by dipaliwagh30** [comment]
> @dipaliwagh30 Try version 2.0.5 for now and let me know if you face same problem again.

@gmerabishvili  Its still not working on windows 10.

**Comment by gmerabishvili** [comment]
@dipaliwagh30  What version are you using?

**Comment by dipaliwagh30** [comment]
> @dipaliwagh30 What version are you using?

I was using 2.0.1

But after your reply I upgraded it to 2.0.5. But still same issue is occurring.

**Comment by dipaliwagh30** [comment]
> @dipaliwagh30 Try latest versions 2.0.7 or 2.0.8 As I tested it works properly.

@gmerabishvili , autocomplete is not working for version 2.0.7 and angular cli 10.0.0 on windows 10.

below are the errors I'm getting:
ERROR in node_modules/angular-ng-autocomplete/lib/autocomplete.component.d.ts:243:21 - error TS2694: Namespace '"C:/Users/waghdip/DMS Bitbucket/Dipali-dev/legaldms/ApplicationCode/Angular/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

243     static ɵfac: i0.ɵɵFactoryDeclaration<AutocompleteComponent, never>;
                        ~~~~~~~~~~~~~~~~~~~~
node_modules/angular-ng-autocomplete/lib/autocomplete.component.d.ts:244:21 - error TS2694: Namespace '"C:/Users/waghdip/DMS Bitbucket/Dipali-dev/legaldms/ApplicationCode/Angular/node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDeclaration'.

244     static ɵcmp: i0.ɵɵComponentDeclaration<AutocompleteComponent, "ng-autocomplete", never, { "data": "data"; "searchKeyword": "searchKeyword"; "placeholder": "placeholder"; "heading": "heading"; "initialValue": "initialValue"; "historyIdentifier": "historyIdentifier"; "historyHeading": "historyHeading"; "historyListMaxNumber": "historyListMaxNumber"; "notFoundText": "notFoundText"; "isLoading": "isLoading"; "debounceTime": "debounceTime"; "disabled": "disabled"; "minQueryLength": "minQueryLength"; "focusFirst": "focusFirst"; "customFilter": "customFilter"; "selectedValueRender": "selectedValueRender"; "itemTemplate": "itemTemplate"; "notFoundTemplate": "notFoundTemplate"; }, { "selected": "selected"; "inputChanged": "inputChanged"; "inputFocused": "inputFocused"; "inputCleared": "inputCleared"; "opened": "opened"; "closed": "closed"; "scrolledToEnd": 
"scrolledToEnd"; }, ["customTemplate"], never>;
                        ~~~~~~~~~~~~~~~~~~~~~~
node_modules/angular-ng-autocomplete/lib/highlight.pipe.d.ts:5:21 - error TS2694: Namespace '"C:/Users/waghdip/DMS Bitbucket/Dipali-dev/legaldms/ApplicationCode/Angular/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

5     static ɵfac: i0.ɵɵFactoryDeclaration<HighlightPipe, never>;
                      ~~~~~~~~~~~~~~~~~~~~
node_modules/angular-ng-autocomplete/lib/highlight.pipe.d.ts:6:22 - error TS2694: Namespace '"C:/Users/waghdip/DMS Bitbucket/Dipali-dev/legaldms/ApplicationCode/Angular/node_modules/@angular/core/core"' has no exported member 'ɵɵPipeDeclaration'.  

6     static ɵpipe: i0.ɵɵPipeDeclaration<HighlightPipe, "highlight">;
                       ~~~~~~~~~~~~~~~~~
node_modules/angular-ng-autocomplete/lib/autocomplete-lib.module.d.ts:7:21 - error TS2694: Namespace '"C:/Users/waghdip/DMS 
Bitbucket/Dipali-dev/legaldms/ApplicationCode/Angular/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

7     static ɵfac: i0.ɵɵFactoryDeclaration<AutocompleteLibModule, never>;
                      ~~~~~~~~~~~~~~~~~~~~
node_modules/angular-ng-autocomplete/lib/autocomplete-lib.module.d.ts:8:21 - error TS2694: Namespace '"C:/Users/waghdip/DMS 
Bitbucket/Dipali-dev/legaldms/ApplicationCode/Angular/node_modules/@angular/core/core"' has no exported member 'ɵɵNgModuleDeclaration'.

8     static ɵmod: i0.ɵɵNgModuleDeclaration<AutocompleteLibModule, [typeof i1.AutocompleteComponent, typeof i2.HighlightPipe], [typeof i3.CommonModule, typeof i4.FormsModule], [typeof i1.AutocompleteComponent, typeof i2.HighlightPipe]>;
                      ~~~~~~~~~~~~~~~~~~~~~
node_modules/angular-ng-autocomplete/lib/autocomplete-lib.module.d.ts:9:21 - error TS2694: Namespace '"C:/Users/waghdip/DMS 
Bitbucket/Dipali-dev/legaldms/ApplicationCode/Angular/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectorDeclaration'.

9     static ɵinj: i0.ɵɵInjectorDeclaration<AutocompleteLibModule>;
                      ~~~~~~~~~~~~~~~~~~~~~


ERROR in Unexpected value 'AutocompleteLibModule in C:/Users/waghdip/DMS Bitbucket/Dipali-dev/legaldms/ApplicationCode/Angular/node_modules/angular-ng-autocomplete/lib/autocomplete-lib.module.d.ts' imported by the module 'AppModule in C:/Users/waghdip/DMS Bitbucket/Dipali-dev/legaldms/ApplicationCode/Angular/src/app/app.module.ts'. Please add a @NgModule annotation
