### ISSUE TITLE
./node_modules/angular-ng-autocomplete/fesm5/angular-ng-autocomplete.js 22:64-80 "export 'defineInjectable' was not found in '@angular/core'

### ISSUE THREAD

**Issue by santhanakrishnanstark** [gmerabishvili/angular-ng-autocomplete#32]
Hi , am using angular 4 and when i try to run the program i got this error ? is there any version problem ???

    ./node_modules/angular-ng-autocomplete/fesm5/angular-ng-autocomplete.js
    22:64-80 "export 'defineInjectable' was not found in '@angular/core'

**Comment by gmerabishvili** [comment]
yes, you should upgrade your app to at least Angular 6 version...
