### ISSUE TITLE
TypeError: Cannot read property 'toLowerCase' of undefined at angular-ng-autocomplete.js:309

### ISSUE THREAD

**Issue by pavangayakwad** [gmerabishvili/angular-ng-autocomplete#33]
Followed step-by-step procedure as shown in basic auto complete and this error popping up.

![image](https://user-images.githubusercontent.com/1834890/62756613-13b4fd80-ba96-11e9-8a66-2a0b39985709.png)

**Comment by KevinBeckers** [comment]
Try to replace [searchKeyword]="keyword" with searchKeyword="keyword".

**Comment by gmerabishvili** [comment]
Check if you provide valid data to an autocomplete like this:
public countries = [
    {
      id: 1,
      name: 'Albania',
    },
    {
      id: 2,
      name: 'Belgium',
    }
]

**Comment by oza75** [comment]
Same issue ! I think it just filter initial data when searching , If we try to fecth items for a server on `onChangeSearch method` we get this error

**Comment by brijesh872** [comment]
Just set variable **keyword = 'name'**  in component.ts file and use as [searchKeyword]="keyword"

**Comment by fquiroz** [comment]
same error

**Comment by totus80** [comment]
i have same error

**Comment by gmerabishvili** [comment]
@fquiroz @totus80 Do you guys use "keyword" property properly?

**Comment by totus80** [comment]
> @fquiroz @totus80 Do you guys use "keyword" property properly?

Hi. It works. My typing error for keywork preperty.
Thanks

**Comment by totus80** [comment]
Hi, can i search with two keywords?

**Comment by gmerabishvili** [comment]
@totus80 Currently you can't search with two keywords, but check this tutorial that might help you in some way in your requirement: https://www.freakyjolly.com/autocomplete-using-angular-ng-autocomplete-package-tutorial-by-example/

**Comment by suryasarafe** [comment]
is anyone solve this.?

**Comment by gvpratap1997** [comment]
i also facing same error

**Comment by rasu06** [comment]
I am still getting the same error, after following above all solutions. please help me regarding the error.

**Comment by elmekkaoui08** [comment]
You just need to initialize the keyword variable in your .ts file
ex: public keyword: string = "";
