### ISSUE TITLE
IE Issue - Item Click is not  firing

### ISSUE THREAD

**Issue by ghost** [gmerabishvili/angular-ng-autocomplete#35]
Steps to replicate - Open in IE 11 browser.

1. Focused the input text
2. When drop down show click on any item.

Temporary fixed - on my fork copy - I changed it to mouse down.

**Comment by karthikeyan-r** [comment]
Hi, I am facing same issue. Autocomplete is showing search results, but click event on the result item is not doing any operation. Please let me know how to resolve it
