### ISSUE TITLE
panel don't close on blur (press tab key)

### ISSUE THREAD

**Issue by Coralie-Lecocq** [gmerabishvili/angular-ng-autocomplete#37]
![image](https://user-images.githubusercontent.com/44767968/63275374-b85aea80-c2a1-11e9-9d07-f24cdccd4bab.png)

**Comment by JojiePalahang** [comment]
@Coralie-Lecocq  - check my forked copy.

**Comment by gmerabishvili** [comment]
Hello, The issue is resolved. Please update to latest 1.1.15 version. Thank you!

**Comment by robinwkurtz** [comment]
This still seems to be an issue in 1.1.15 and even 2.0.1
