### ISSUE TITLE
angular 7 - missing peer dependency

### ISSUE THREAD

**Issue by DayVidZhou** [gmerabishvili/angular-ng-autocomplete#38]
Currently on Angular: 7.2.15
I get the warning
npm WARN angular-ng-autocomplete@1.1.14 requires a peer of @angular/common@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-ng-autocomplete@1.1.14 requires a peer of @angular/core@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by aerypton** [comment]
I have the same warning with Angular 8.0.3

**Comment by MichaelTurbe** [comment]
Hi, do you plan to upgrade the project to build correctly with Angular 7 and 8?

**Comment by gmerabishvili** [comment]
@MichaelTurbe Hello, yes, I do. Do you have any other issues beside missing peer dependencies
 in Angular 7 and 8?

**Comment by MichaelTurbe** [comment]
No, thankfully, we have no other issues beyond the peer dependency
mismatch. Thanks!

**Comment by gmerabishvili** [comment]
Hello, The issue is resolved. Please update to latest 1.1.15 version. Thank you!
