### ISSUE TITLE
input autofocus

### ISSUE THREAD

**Issue by amarshilpakar** [gmerabishvili/angular-ng-autocomplete#41]
How to make input focused when initialized.

**Comment by JojiePalahang** [comment]
Hi @amarshilpakar - Please see the readme and you can check the available methods you can invoke.
Sample code is available as well.
![image](https://user-images.githubusercontent.com/19182512/64001180-e0680a80-cb39-11e9-8fb0-6de70b409505.png)

**Comment by amarshilpakar** [comment]
Hi @JojiePalahang 
I have tried those methods but is not working..
 Here is stackblitz link 

https://stackblitz.com/edit/angular-ng-autocomplete-5blo79

**Comment by JojiePalahang** [comment]
Hi @amarshilpakar can you tell me whats your goal? by default the original code it does not auto focus the input text, but what it does it open the suggestion panel if the data is not empty.

see this line of code it was commented by the author.
![image](https://user-images.githubusercontent.com/19182512/64229684-0bc56d80-cf1d-11e9-8e5a-1573d6870cbb.png)

I tried and It invoke the method focus and it fires.

 ![image](https://user-images.githubusercontent.com/19182512/64229577-c30db480-cf1c-11e9-9d42-88134e87c9a9.png)
![image](https://user-images.githubusercontent.com/19182512/64229619-d9b40b80-cf1c-11e9-8589-69ead1ce34d4.png)

**Comment by Quethzel** [comment]
That solution didn't work for me. I use the following code:

`this.input.element.nativeElement.firstChild.firstElementChild.firstElementChild.focus();`

**Comment by Anas-Chrono** [comment]
Hi @gmerabishvili . what is the solution for this?. can you please me out. i tried this.auto.open() in ngOnInit. its not working as expected.

**Comment by gmerabishvili** [comment]
@Anas-Chrono And what is the problem exactly? "this.auto.open()" in ngOnInit should have worked if the data isn't empty. Can you share the code on Stackblitz please?

**Comment by Anas-Chrono** [comment]
@gmerabishvili Yes i had a data. Forked your code and updated a focus things in here. This is the stuff i had done with my code. [stackblitzcode](https://stackblitz.com/edit/angular-ng-autocomplete-3zvsly?file=src/app/app.component.ts)

**Comment by gmerabishvili** [comment]
@Anas-Chrono Try this way:   
ngOnInit() {
    setTimeout(()=>{
      this.auto.focus();
    })
  }

**Comment by Anas-Chrono** [comment]
@gmerabishvili Thanks for that. its opening a suggestion while init. but i want a cursor to focus in a input. do you had something for that

**Comment by Anas-Chrono** [comment]
Hai @gmerabishvili this.auto.focus is opening a suggestion. but the cursor is not in the text box. i want to put a cursor on input. Can you please help me out.

**Comment by gmerabishvili** [comment]
Hello @Anas-Chrono , The focus issue is resolved. Please update to latest 1.1.15 version. Thank you!
