### ISSUE TITLE
Change type input autocomplete

### ISSUE THREAD

**Issue by guiltm** [gmerabishvili/angular-ng-autocomplete#43]
Is possible change the type input of autocomplete?
Example, need only numbers input (type='number').

**Comment by guiltm** [comment]
I maked other changes in the component, how load the data when the scroll are 30% to the end list, and not just when in the end of list (to user not wait  much when 
scrolling to the list ), and other things, the component is very good :)

**Comment by gmerabishvili** [comment]
Hello, from the Autocomplete definition perspective that functionality can't be the part of the library. You can create your own directive for stuff like that. Thank you.
