### ISSUE TITLE
Search icon is missing

### ISSUE THREAD

**Issue by Amitshaale** [gmerabishvili/angular-ng-autocomplete#44]
Can you please put search icon on right side of the input.

**Comment by Amitshaale** [comment]
magnifying glass in side input field like you have remove icon on right.

**Comment by gmerabishvili** [comment]
Can't understand. Can you give me more details what you mean?

**Comment by Amitshaale** [comment]
![Screenshot 2019-09-30 at 3 27 05 PM](https://user-images.githubusercontent.com/50046070/65869024-2ad9e280-e397-11e9-8bc0-afa12e891103.png)

**Comment by gmerabishvili** [comment]
This is autocomplete component, not some search box. So, if you like to have that kind of functionality you can make it for your own according to your requirements.
