### ISSUE TITLE
Could we get the ability to change the input type to prevent browser autocomplete?

### ISSUE THREAD

**Issue by Octopixell** [gmerabishvili/angular-ng-autocomplete#45]
Would it be possible to get an update to also allow changing the input type of the search field. 

Personally I would like to set the type to `search` to prevent browsers from popping up their own autocomplete which destroys the user experience.

I've seen other issues like #43 that would like a `number` type field. 

I don't mind making a PR if I could find out which project to fork and update. Maybe you could tell me that and I'll make the PR so everyone can enjoy this feature?

Thanks.

**Comment by gmerabishvili** [comment]
Hello @Octopixell Can you provide an example of this issue in Stackblitz please? Because I checked and no browser autocomplete pops out by default.
