### ISSUE TITLE
Library fails to work if class is used instead of object for data input

### ISSUE THREAD

**Issue by Eivyses** [gmerabishvili/angular-ng-autocomplete#46]
Hello. Sorry if I write this in bad structure, but i haven't done it before. So, there's a bug in autocomplete with classes. If i provide interface like this:
```
export interface Test {
  id: number
  name: string
}
```
And after that I initialize interface and give it as `data` to autocomplete:
```
testData: Test[] = [
{
  id: 2,
  name: 'hello'
},
{
  id: 4,
  name: 'test'
}]
```
Everything works as expected. But, If i were to replace interface with class
```
export class Test {
  id: number;
  name: string;

  constructor(id: number, name: string){
    this.id = id;
    this.name = name;
  }
}
```
And after that and give it as `data` to autocomplete:
```
testData: Test[] = [];
testData.push(new Test(2, 'hello'));
testData.push(new Test(4, 'test'));
```

Autocomplete simply won't work. Nothing will be shown.
I did go through code and found out the reason it is not working on line
https://github.com/gmerabishvili/angular-ng-autocomplete/blob/0ebdefb27635fd6382246ab2b041be0c00b1aaaa/projects/autocomplete-lib/src/lib/autocomplete/autocomplete.component.ts#L234

When i give concrete class the `item.constructor` contains:
```
ƒ Test(id, name) {
        this.id = id;
        this.name = name;
    }
```

instead of expected
```
ƒ Object() { [native code] }
```

My solution is to change `&& item.constructor === Object` into `&& item instanceof Object`

**Comment by gmerabishvili** [comment]
Hi @Eivyses Just tested and it works perfectly. I think there's something wrong with your implementation.

**Comment by Eivyses** [comment]
@gmerabishvili hey. I did create a demo, but i can't share a full link to it. Open [plunker](https://embed.plnkr.co/plunk/9GPbP6) and paste to it all the code from this file
[demo_project.zip](https://github.com/gmerabishvili/angular-ng-autocomplete/files/4031250/demo_project.zip)

**Comment by gmerabishvili** [comment]
@Eivyses You can provide an example in Stackblitz and you can share the full link here.

**Comment by Eivyses** [comment]
@gmerabishvili thanks for providing the page. here's the [example](https://stackblitz.com/edit/angular-ng-autocomplete-class-bug?embed=1&file=src/app/app.component.ts)

**Comment by gmerabishvili** [comment]
Hello @Eivyses. The issue is fixed. Please upgrade to latest 2.0.2 version. Thank you!
