### ISSUE TITLE
Filter problem

### ISSUE THREAD

**Issue by raphagood** [gmerabishvili/angular-ng-autocomplete#49]
I have a problem that I can not solve, I am performing a search in my database but the keyword is treated, I realized that when the return comes, it is displayed that no records were found, because what was searched for example RESSONANCIA is different from the RESSONÂNCIA result (No ^), I would like it not to filter the result by the keyword this is possible, ie I just want to show me the result of the api.

**Comment by carbler** [comment]
Tengo el mismo problema, ¿Hay alguna forma de que no tenga en cuenta los acentos?

**Comment by gmerabishvili** [comment]
Hello, @raphagood, @carbler  can you provide an example in Stackblitz please?

**Comment by fmrz1996** [comment]
Hey! I have the same problem, when I try to search a word like "canción" and I write "cancio...", the option stops to seem. I need a non-sensitive search.

**Comment by gmerabishvili** [comment]
I think you must handle it yourself in Backend side.
