### ISSUE TITLE
Panel close automatically clean input

### ISSUE THREAD

**Issue by tosipaulo** [gmerabishvili/angular-ng-autocomplete#5]
This lib is very great, congratulations !!

I have a question, I am trying to close the panel automatically when the input is clean, reading the documentation it triggers the event `(inputCleared)`.

Even though I'm using #auto and activating `this.auto.close()` it does not close!

Could you help me with that?

[https://stackblitz.com/edit/angular-mapkmv](https://stackblitz.com/edit/angular-mapkmv)

Thank you ☺

**Comment by gmerabishvili** [comment]
Hello, thanks for the report. The issue is resolved. Please update to latest 1.1.11 version and let me know if everything is OK. Thank you! : )

**Comment by tosipaulo** [comment]
Hello,

I updated your lib to 1.1.11, but I could not close the paniel.
I used the method:
```
(inputChanged)='onChangeSearch($event)'

onChangeSearch(e){
    if(!e.length) {
      this.auto.close();
    }
    /** do something **/
  }
```
And also:
```
(closed)="closedStatic()"
closedStatic() {
    this.auto.close();
  }
```
Can you help me?

[Demo Link](https://stackblitz.com/edit/angular-mapkmv)

**Comment by tosipaulo** [comment]
Hello,

I've updated your lib to 1.1.11, but I'm not able to automatically close the panel when the number of characters is zero in the input.

I created this medit, but it did not work:
```
onChangeSearch(search: string) {
    if(!search.length) {
      this.auto.close();
    }
  }
```

and also
```
onCleared(e) {
    console.log("onCleared");
    this.auto.close();
  }
```
 Would you help me?

[Demo link](https://stackblitz.com/edit/angular-fganqn)

Thank you! : )

**Comment by gmerabishvili** [comment]
Okay. I'll check it right now. BTW why do you need to close the panel on focus? 
  onFocused(e) {
    console.log("onFocused")
    this.auto.close();
  }

**Comment by tosipaulo** [comment]
Because the panel can only open after search is found on the data and close when the input length is zero, I need to close it.
;)

**Comment by ytnydv** [comment]
Hi Dev, Thanks for awesome component.

Am also trying to find solution for same situation mentioned above. Your help will be appreciated.

**Comment by gmerabishvili** [comment]
Hello, sorry for late response. I was too busy : ) I fixed that issue. Please update to latest 1.1.12 version, test it in all your scenarios and let me know if everything works. Thank you.

**Comment by tosipaulo** [comment]
@gmerabishvili  thanks, everything worked! Your lib will help thousands of devs = D
