### ISSUE TITLE
Trigger open on focus

### ISSUE THREAD

**Issue by knot-kraljevo** [gmerabishvili/angular-ng-autocomplete#50]
I have method which works on input focus in autocomplete and I defined autocomplete as ViewChild.
But when I try to open autocomplete (this.autocomplete.open()) on focus it wont open. I just want to open autocomplete on first focus without typing anything.

**Comment by gmerabishvili** [comment]
Hello, can you provide an example in Stackblitz please?

**Comment by gmerabishvili** [comment]
Actually If get your issue right as default it works like you described: Autocomplete opens on input focus:)

**Comment by Anas-Chrono** [comment]
Hai @gmerabishvili, how should we open a autocomplete panel after typing a value and not in first focus.

**Comment by gmerabishvili** [comment]
Hi, @Anas-Chrono you can do it this way:
  onFocused(e) {
    this.auto.close();
  }
And it will be close on focus.

**Comment by Anas-Chrono** [comment]
Thanks @gmerabishvili its Working Great.

**Comment by rVethencourt** [comment]
Hi, 

> Hi, @Anas-Chrono you can do it this way:
> @ViewChild('auto') auto;
> onFocused(e) {
> this.auto.close();
> }
> And it will be closed on focus.

Hi, how would this work with angular 8? The change to ViewChild in this version is making this.auto undefined when onFocused is triggered.

**Comment by gmerabishvili** [comment]
@rVethencourt I think you're you missing the template reference variable: 

<div class="ng-autocomplete">
<ng-autocomplete #auto></ng-autocomplete>
</div>

**Comment by rVethencourt** [comment]
I'm not, it's there.

`<div class="ng-autocomplete mb-4">
        <ng-autocomplete #auto [data]="usersCable" [searchKeyword]="userKey"
        [formControl]="username" (selected)='onUserSelect($event)'
        (inputChanged)='searchUsers()' (inputFocused)="onFocused()"
        (inputCleared)="onCleared()" [historyIdentifier]="null"
        [itemTemplate]="itemTemplate" [notFoundTemplate]="notFoundTemplate"
        notFoundText="Nothing found." placeholder="@username"
        minQueryLength="3">`

`@ViewChild('auto', {static: true, read: true}) auto;`

`onFocused() {
    this.auto.close(); // ERROR 'auto' is undefined
  }`

**Comment by gmerabishvili** [comment]
@rVethencourt Try @viewChild  static: false. I tested it in Angular 8 and it works properly. I think There's something wrong in your implementation.

**Comment by knot-kraljevo** [comment]
I found what was an issue in my case. I have 2 autocomplete one next to another and for some reason if i place ngModel on the first one it wont open on focus first time. If you start typing something and close autocomplete than it will work. I just changed ngModel with initialValue and it seems it's working fine.
