### ISSUE TITLE
Expose Control State (pristine, untouched, etc)

### ISSUE THREAD

**Issue by kmb385** [gmerabishvili/angular-ng-autocomplete#51]
This may be user ignorance, but it would be nice if you could access the state of the control for use in template driven forms.  I would like to be able to determine if the control is pristine, touched, etc similar to native angular template reference variables.

This could be achieved through the component markup or when adding the component as a @ViewChild in a typescript file.

I'm simply looking for a way to do some simple validation against this control such as making it required.

**Comment by gmerabishvili** [comment]
Hello, actually you can apply all controls validation (pristine, touched and etc) on autocomplete as you would on normal input.  It works.
