### ISSUE TITLE
ng-autocomplete [disabled]=true not working

### ISSUE THREAD

**Issue by Sagar4412** [gmerabishvili/angular-ng-autocomplete#52]
<div class="ng-autocomplete">
                      <ng-autocomplete #make [placeHolder]="'Vehicle Make'" [data]="makeList"
                        [(ngModel)]="selectedMakelist.VehicleMake" [ngModelOptions]="{ standalone: true }"
                        [searchKeyword]="keyword" (selected)="selectEvent($event)" [itemTemplate]="itemTemplate"
                        [notFoundTemplate]="notFoundTemplate" [disabled]=true></ng-autocomplete>
                      <ng-template #itemTemplate let-item>
                        <a [innerHTML]="item.VehicleMake | safeHtml"></a>
                      </ng-template>
                      <ng-template #notFoundTemplate let-notFound>
                        <div [innerHTML]="notFound | safeHtml"></div>
                      </ng-template>
                    </div>

**Comment by gmerabishvili** [comment]
@Sagar4412 Just tested and it works without any problem. Can you share your code in Stackblitz please?

**Comment by Sagar4412** [comment]
@gmerabishvili I Just want to disabled autocomplete text box. Is that working at your end?
Please look at this screenshot: https://imgur.com/GdScExC

**Comment by gmerabishvili** [comment]
@Sagar4412 yes, It works like normal input disable would.
