### ISSUE TITLE
Problem with Style, does not get applied

### ISSUE THREAD

**Issue by NA-Jalilius** [gmerabishvili/angular-ng-autocomplete#56]
Hello there @gmerabishvili , I hope that you're doing great,

My issue is regarding the styling of the Ng-Autocomplete, I don't succeed to apply the style that I want to apply on the component, even that I can get the result using the browser, when using the "ng-autocomplete" class, nothing happen.

PS : I made some research in old posts before asking, I believe it's something close to what you've talked about here https://github.com/gmerabishvili/angular-ng-autocomplete/issues/40#issuecomment-526346142 ; but trying that out didn't work for me too, actually, the /deep/ isn't accepted by .css nor .scss style-sheets. 

I would be very thankful if you could point me what I might be doing wrong, or what do I need to do to get the needed result.

Thank you in advance =) !

**Comment by gmerabishvili** [comment]
Hello @NA-Jalilius , thanks I'm fine. I hope that you're doing great also : )
I think you're using Angular 8 and since version 8 you must use ::ng-deep instead of /deep/. Thank you.

**Comment by NA-Jalilius** [comment]
I'm doing great too, Thank a lot @gmerabishvili  =) 
Thanks also for the quick response, it worked ! Thank you for this wonderful component.
Wishing you the best luck ! 
Closing this issue
