### ISSUE TITLE
cannot serve app with Ivy 

### ISSUE THREAD

**Issue by AmaelN** [gmerabishvili/angular-ng-autocomplete#57]
It seems that this piece of code cannot be used with Ivy 

` // custom templates
  @ContentChild(TemplateRef)
  @Input() itemTemplate: TemplateRef<any>;
  @Input() notFoundTemplate: TemplateRef<any>;`

As I'm getting the following error message

 Cannot combine @Input decorators with query decorators

Need help on this part.

Thanks

**Comment by AmaelN** [comment]
Angular suggestion :

This is not supported in Ivy and as a possible solution, you can assign decorators to different class fields and use the value from the second field if the first one is not defined.
Source: https://github.com/angular/angular/issues/31398

**Comment by AmaelN** [comment]
In _autocomplete.component.html_

Change `itemTemplate` to `itemTemplate?itemTemplate:customTemplateRef`

And in _autocomplete.component.ts_

change this code 

```
  @ContentChild(TemplateRef)
  @Input() itemTemplate: TemplateRef<any>;
```
to 

```
@ContentChild(TemplateRef) customTemplateRef;
@Input() itemTemplate: TemplateRef<any>;
```

I'm not able to compile your code as you are using angular 6 and I'm currently using angular 8. i'm testing Ivy before the release of Angular 9 in the coming weeks which will use Ivy only.

Please test this change and let me know if you create a new version that will work with Ivy

Thanks in avance

**Comment by AmaelN** [comment]
I've tested it and generated the new package and I tried to build with Ivy and it worked well...

I've tried to push a commit to a new branch without success to you repository.

Please apply the change to it as I'm not able for some reason to push new branch to your repo

**Comment by AmaelN** [comment]
I leave it open as someone might look for it
...Also until the owner fix the issue

**Comment by uplink42** [comment]
I get the same error after updating to v9 with Ivy.

**Comment by QuattroViper** [comment]
I also have the same problem. This library is also quite heavily used in our environment and I would really appreciate it, if the owner would update the package.

**Comment by AmaelN** [comment]
He will work on it eventually, (or someone will have to take ownership of this project)
I suggest you to use the fix suggested as it is really easy to implement...

**Comment by QuattroViper** [comment]
Hi. Yess I implemented the fix myself and it is working.
I wil use the library again when it's supports angular 9

**Comment by gmerabishvili** [comment]
Hello, I will update the library on Angular 9 as soon as possible. Thank you! <3

**Comment by gmerabishvili** [comment]
Hello everyone, The library is upgraded to Angular 9 : )  Please update to latest 2.0.1 version. Thank you!
