### ISSUE TITLE
Style is scoped global

### ISSUE THREAD

**Issue by Dimitriio** [gmerabishvili/angular-ng-autocomplete#59]
Hello @gmerabishvili ,

I have an issue regarding the styling of the Ng-Autocomplete, it seems that it is not scoped only for the component. I checked the source code and saw this:
`  encapsulation: ViewEncapsulation.None,`
It bothers me to have side effects when using a library :/ (i saw it because the i am using "overlay" class too in my app)
Is it possible having styles that are encapsulate (like the default one) ?

Thank you in advance.
@Dimitriio

**Comment by venelinn** [comment]
Hi @Dimitriio ,
I guess this should be optional. 
It's always better to fix your css rather than asking people to fix theirs. 
Also consider using BEM, then you shouldn't have any issues with css overwriting.

**Comment by gmerabishvili** [comment]
@Dimitriio I use ViewEncapsulation.None intentionally to make styling easier from outside. So, it makes sense. Thank you.
