### ISSUE TITLE
How to clean input when selected.

### ISSUE THREAD

**Issue by vCodeTech** [gmerabishvili/angular-ng-autocomplete#6]
Hello, I want clear input search when event selected active. Can you help me.

**Comment by kawaalsaleem** [comment]
First off, I really love the module, it's easy to use.
But I'd also like the option to clear the text input from code.

**Comment by gmerabishvili** [comment]
Hi, could you provide more details about the issue? I couldn't understand exactly when you want to clear the input...

**Comment by gmerabishvili** [comment]
Hello, I added the control to clear the input manually. Please re-check the documentation and update to latest 1.1.12 version. Thank you.
