### ISSUE TITLE
After clearing and closing the autocomplete programmatically you cannot open the suggestions popup on next click

### ISSUE THREAD

**Issue by ankurkgupta** [gmerabishvili/angular-ng-autocomplete#60]
If you clear and close the autocomplete from code using methods clear() and close() then on the next click in the input box, the suggestions popup is not displayed.

Below is a stackblitz link to reproduce the issue.

https://stackblitz.com/edit/angular-ng-autocomplete-dlpg6p

In the above example select any value from list. Then click on button "Clear & Close"
Now when you click back on the input box, the suggestions popup is not shown. 
To have the popup again, you need to click on the input box, then click out of it once and then click on it back.

**Comment by jayudhandha** [comment]
+1

**Comment by jayudhandha** [comment]
In **autocomplete.component.ts** [[Link]](https://github.com/gmerabishvili/angular-ng-autocomplete/blob/master/projects/autocomplete-lib/src/lib/autocomplete/autocomplete.component.ts) See,

```
close() {
    this.manualClose = true;
    this.isOpen = true;
    this.handleClose();
  }
```

It seems when you call the `close` function, It calls `handleClose()` internally.

```
 handleClose() {
    if (!this.isOpen) {
      this.isFocused = false;
      return;
    }
    this.isOpen = false;
    this.overlay = false;
    this.filteredList = []; // Here we are clearing the list
    this.selectedIdx = -1;
    this.notFound = false;
    this.isHistoryListVisible = false;
    this.isFocused = false;
    this.closed.emit();
  }

```
[Source](https://github.com/gmerabishvili/angular-ng-autocomplete/blob/master/projects/autocomplete-lib/src/lib/autocomplete/autocomplete.component.ts#L455-L468)

This function is clearing `filteredList`, So according to me either we should refresh this lise (Using this.filterList();) or we should not clean the `filteredList` when we close.

@gmerabishvili Please correct me if i am wrong, Awaiting your input!

Thanks,
Jayesh

**Comment by gmerabishvili** [comment]
Hi @jayudhandha The solution here is to just call close() before clear() and it will work. Like this:
```
  onClear() {
    this.autoComplete.close();
    this.autoComplete.clear();
  }
```
