### ISSUE TITLE
Input not handling html entities

### ISSUE THREAD

**Issue by xKrr** [gmerabishvili/angular-ng-autocomplete#66]
Hi mate!

I was trying your component and it works like a charm! But since itemTemplate and notFoundTemplate can print html entities like M\&#225;laga , the search input is not able to do it :_(.

I've tried to reproduce it with one of your stackblitz examples and its happening there as well. 

https://stackblitz.com/edit/angular-ng-autocomplete-with-images-qubbbe?file=src/app/app.component.ts

**Comment by gmerabishvili** [comment]
@xKrr Hello, so, what's your suggestion to do in this case? I think it's user's responsibility not to use obscure symbols or entities in searchKeyword property. Thank you.
