### ISSUE TITLE
ERROR TypeError: Cannot read property 'nativeElement' of undefined

### ISSUE THREAD

**Issue by blackWhitePanda** [gmerabishvili/angular-ng-autocomplete#67]
I have just install the package with latest version(1.1.15). I followed the Usage sample in **Getting started** but found the following issue. Seems, it is fail to get `this.filteredListElement`

![image](https://user-images.githubusercontent.com/55032927/72344277-cce5c680-370b-11ea-8a49-1e57a09f9478.png)

![image](https://user-images.githubusercontent.com/55032927/72345734-61055d00-370f-11ea-841b-4633705d3c50.png)

**Comment by gmerabishvili** [comment]
Hi @blackWhitePanda, I think you're doing something wrong. Can you provide an example of your implementation is Stackblitz?

**Comment by blackWhitePanda** [comment]
It is fine in pure angular project, so if I redo the sample code in Stackblitz, it works without any problem.

However, my project is built based on core-ui template. I tried to redo the sample code in pure core-ui template, but it fails. So, you may reproduce the issue if you git clone the project https://github.com/coreui/coreui-free-angular-admin-template.git.

Here is the detail of core-ui:
https://github.com/coreui/coreui-free-angular-admin-template/

Seems, it is a compatibility issue.

**Comment by gmerabishvili** [comment]
Hello @blackWhitePanda I've upgraded the library to Angular 9.  Please update to latest 2.0.1 version and test with core-ui template. I think the issue is resolved, but If it still persists then there's something wrong with core-ui template. Thank you.
