### ISSUE TITLE
In some countries,Material icons cannot be loaded 

### ISSUE THREAD

**Issue by TheColdVoid** [gmerabishvili/angular-ng-autocomplete#69]
I think the AutoComplete library you wrote is awesome, and I think it works. However, I and my users are in mainland China, because of national policy reasons, can not access GoogleAPI (including Google's Material Design icon resources). So, can you give me a way to replace the icon library, I will replace it with a domestic Google API mirror station, so that my APP can be accessed normally in mainland China. Thank you.
![image](https://user-images.githubusercontent.com/10008227/72748415-28bfbc00-3bf2-11ea-996d-d92d841f307e.png)

**Comment by gmerabishvili** [comment]
Hi, @TheColdVoid Do you use Font Awesome or any other custom fonts for icons? If yes you can write a scss mixin that will replace Material fonts with other one. Example:
```
@mixin icon-override_mat($icon) {
  background: none !important;
  font-family: 'your icon font family'; // e.g fontawesome
  speak: none;
  font-style: normal;
  font-weight: normal;
  font-variant: normal;
  text-transform: none;
  line-height: 1;
  display: inline-block;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-indent: 0px !important;
  text-align: center;

  &:before {
    content: $icon;
  }
}
```

**Comment by TheColdVoid** [comment]
> Hi, @TheColdVoid Do you use Font Awesome or any other custom fonts for icons? If yes you can write a scss mixin that will replace Material fonts with other one. Example:
> 
> ```
> @mixin icon-override_mat($icon) {
>   background: none !important;
>   font-family: 'your icon font family'; // e.g fontawesome
>   speak: none;
>   font-style: normal;
>   font-weight: normal;
>   font-variant: normal;
>   text-transform: none;
>   line-height: 1;
>   display: inline-block;
>   -webkit-font-smoothing: antialiased;
>   -moz-osx-font-smoothing: grayscale;
>   text-indent: 0px !important;
>   text-align: center;
> 
>   &:before {
>     content: $icon;
>   }
> }
> ```

Thank you for your patience to answer, I solved this problem with this method
