### ISSUE TITLE
changing [(ngModel)] programmatically

### ISSUE THREAD

**Issue by idandvd** [gmerabishvili/angular-ng-autocomplete#7]
Hi,

Great tool!! thank you.

I have a problem when trying to change [(ngModel)] from the ts file or when the ng-autocomplete is in ngIf Div and the condition changes from true to false and to true again.

What happens is that I have an item selected and shows up great, but when I change the ngIf condition to false and then to true the text changes to "[object Object]".

The same thing happens when I change the value of the varible inside the ngModel to another item from the list.

Example:
html file:

```
<ng-autocomplete [data]="mothers" [searchKeyword]="keyword"
                 [itemTemplate]="itemTemplate" [(ngModel)]="selectedMother">
</ng-autocomplete>
<ng-template #itemTemplate let-item>
    <a [innerHTML]="item.FirstName"></a>
</ng-template>
```

TS file:
```
this.selectedMother = this.mothers[1];
// if the selectedMother is already mothers[1] then nothing happens,
// but if the selectedMother is mother[0] for example then the text changes to "[object Object]".
```

I need to be able to select an item from ts file. Is that possible?
Thanks.

**Comment by gmerabishvili** [comment]
Hello, As I guess you have an array of objects and you're doing something wrong.  I think you must do something like this: "this.selectedMother = this.mothers[0]. FirstName".  Not "this.selectedMother = this.mothers[0]" which is an object.

**Comment by idandvd** [comment]
Yes, you are correct, it is an array of objects, but it works just fine for everything other then setting the model in the ts file.
If I write "this.selectedMother = this.mothers[0].FirstName" then the text will show the right name but the object selected will be just the name instead of the "mother" object.
I think that what's happaning is that when setting the model outside the html form, the text box shows the toString of the object instead of the keyword property specified in the element.
Have a look at this:
https://stackblitz.com/edit/angular-ng-autocomplete-with-forms-bomg6s
I think the solution is easy, isn't?

**Comment by gmerabishvili** [comment]
Hello, sorry for late response. I was too busy : )  Yes, it's easy and here is the solution: 
// ts file
selected: any = '';
  public countriesTemplate = [{name: 'Albania'}, {name: 'Andorra'}, {name: 'Armenia'}, {name: 'Austria'}];
  set() {
    this.selected = this.countriesTemplate[2];
  }
// html file
[ngModel]="selected.name".

That's all : )  
P.S  please update the library to 1.1.12 version. Thank you.

**Comment by Dhamu143** [comment]
https://github.com/gmerabishvili/angular-ng-autocomplete/issues/19
