### ISSUE TITLE
Errors when AutoComplete not having data

### ISSUE THREAD

**Issue by alexanderbahmatov** [gmerabishvili/angular-ng-autocomplete#70]
I've found an error.
If AutoComplete doesn't have any values in data property then AutoComplete doesn't get "active" class by ngClass and it doesn't have "z-index:999" property. 
As result notFoundTemplate is overlaid on another elements in DOM (notFoundTemplate looks like on the screenshoot under the text). 
The error is founded in AutocompleteComponent.prototype.open in condition this.data && this.data.length.

And there is another error with the "Clear" button. The button does not close AutoComplete as expected, but the button itself disappears on click

![start](https://user-images.githubusercontent.com/21189369/73250036-e260f300-41d7-11ea-89d9-7ae6f7abc880.PNG)
![not found](https://user-images.githubusercontent.com/21189369/73250044-e4c34d00-41d7-11ea-99b3-5eb163b27cd5.PNG)
![clear not works](https://user-images.githubusercontent.com/21189369/73250047-e7be3d80-41d7-11ea-979d-308d930eeba6.PNG)

**Comment by alexanderbahmatov** [comment]
Add: when press backspace (second screenshot situation) - notFoundTemplate starts work normally (overlaying other elements), isOpen assigned to true, ngClass.active assigned to true and AutoComplete having z-index:999

**Comment by alexanderbahmatov** [comment]
example on stackblitz https://stackblitz.com/edit/angular-yaehvl

**Comment by gmerabishvili** [comment]
Hi @alexanderbahmatov , Just tested your Stackblitz example and it works normally. I think you were doing something wrong or let me know further details regarding the issue.

**Comment by alexanderbahmatov** [comment]
Hi @gmerabishvili , in example you typing in field some text and dont see problem? look at screenshot
![image](https://user-images.githubusercontent.com/21189369/75095116-9aa17180-55b3-11ea-8c2a-850c9a26ad07.png)

**Comment by gmerabishvili** [comment]
Hello @alexanderbahmatov The issue is fixed. Please upgrade to latest 2.0.2 version. Thank you!
