### ISSUE TITLE
Need search with multi keyword.

### ISSUE THREAD

**Issue by moomdate** [gmerabishvili/angular-ng-autocomplete#71]
I need search with multi keyword.
now use only one keyword like search with name - keyword = "name"
some time i want to search with id and name  but lazy to write new methode
i need define keyword with array like this
> searchKeyword:string;

to

> searchKeyword:any[];
> ex. keyword = ["name", "id]

hope you  accept my requirement. 
thank. 💃

**Comment by nawaz2013** [comment]
Yes i have similar requirement. I need to search with name and id too.

**Comment by moomdate** [comment]
> Yes i have similar requirement. I need to search with name and id too.

another way for search multi keyword you can map new array for search like this ->

> new keyword ->>> keyword =  ["name : id"] (type is string).

**Comment by maihannijat** [comment]
This would be a great feature. I am using this package for the address. Currently, my keyword is a city but I want the user search with a street address and province too. I believe there are plenty of other use cases for which this feature is helpful. 

Thanks for regular mainting this.

**Comment by hmzlam** [comment]
the easiest way to do this is to add a feature [filterFunction]="function(items,searchString){return items.filter(.....)}"

**Comment by khocef** [comment]
this would be a great feature, thanks

**Comment by kaushal235** [comment]
For workaround Backend or data add new field with concatenated data & use as this new field for search keyword

**Comment by eewsa** [comment]
> Workaround: In data add new field with concatenated fields & use as this new concatenated field for search keyword

Thank's. It's worked perfectly for me.

**Comment by Aman-Sahota** [comment]
> Workaround: In data add new field with concatenated fields & use as this new concatenated field for search keyword

Thanks it worked perfectly. I had two fields firstName and lastName in array og objects,  so I added a new prop with Name:firstName+' '+lastName and it worked just as I wanted

**Comment by gmerabishvili** [comment]
Hello everyone, `customFilter` feature is implemented, which resolves this particular issue as well. Please check the docs and upgrade to latest 2.0.5 version. Thank you.

**Comment by hmzlam** [comment]
Thank you

**Comment by gmerabishvili** [comment]
Here is the example of autocomplete with multi keyword search :  https://stackblitz.com/edit/angular-autocomplete-search-with-multi-keyword

**Comment by amadoutidiane** [comment]
@gmerabishvili i'am new can give me a code who can help my, read documentation but i don't undestand

**Comment by gmerabishvili** [comment]
@amadoutidiane  Check this Stackblitz https://stackblitz.com/edit/angular-autocomplete-search-with-multi-keyword or check newly added property `selectedValueRender `:  [https://github.com/gmerabishvili/angular-ng-autocomplete/pull/161](url)
