### ISSUE TITLE
Deleting a selected option sometimes causes the component to become unresponsive

### ISSUE THREAD

**Issue by freilich-am** [gmerabishvili/angular-ng-autocomplete#72]
In our app we have a dropdown that pulls options from an API. Whenever I start typing in to the box and select an option (e.g. 'Option 1') and then click into the text at the beginning of the line and then do Ctrl+K deleting the line, I get a console error saying "ERROR TypeError: Cannot read property 'length' of undefined at fL.onKeyUp" and then when I try to type into the box to select another option, it no longer pulls from the API. We saw this error/unresponsiveness sometimes if we delete the text too quickly or sometimes on simply loading the page but the Ctrl+K step is the most reliable way to recreate it. I think I have a fix for this and will put in a PR but would love to know if the fact that I'm seeing this issue in the first place means that I should be using the library differently.

**Comment by freilich-am** [comment]
https://github.com/gmerabishvili/angular-ng-autocomplete/pull/73 is the pull request.

**Comment by MichaelTurbe** [comment]
Hiya folks, I'm having this same issue!  Any chance we could get this PR pulled in?

**Comment by delfinogomes** [comment]
I'm also having this issue. Is anything missing in the PR or there any way to help to fix this?

**Comment by MichaelTurbe** [comment]
I tried patching the code myself with the PR, and it worked great.  Any reason why we couldn't get this pulled in?

**Comment by gmerabishvili** [comment]
Hello everyone, sorry for delay. The issue is fixed based on @freilich-am  pull request. 
Please update to latest 1.1.17 version and let me know if everything is OK. Thank you!
