### ISSUE TITLE
Issue after upgrade to Angular 9.x

### ISSUE THREAD

**Issue by superpotatos** [gmerabishvili/angular-ng-autocomplete#75]
I receive errors after upgrading my project from Angular 8.x to Angular 9. 
I'm using angular-ng-autocomplete v.1.1.16. 
The error is here below:

> ERROR in Failed to compile entry-point angular-ng-autocomplete (es2015 as esm2015) due to compilation errors:
node_modules/angular-ng-autocomplete/fesm2015/angular-ng-autocomplete.js:949:20 - error NG1006: Cannot combine @Input decorators with query decorators
949     itemTemplate: [{ type: ContentChild, args: [TemplateRef,] }, { type: Input }]

Is it possible to please fix this?

Thank you

**Comment by gmerabishvili** [comment]
The library will be upgraded to Angular 9 soon. Thank you.

**Comment by zerowww** [comment]
@gmerabishvili  Do you know approximately when it will be ready for Angular 9 ?

Thanks !

**Comment by zerowww** [comment]
@gmerabishvili  Do you know approximately when it will be ready for Angular 9 ?

Thanks !

**Comment by gmerabishvili** [comment]
Hello everyone, The library is upgraded to Angular 9 : )  Please update to latest 2.0.1 version. Thank you!
