### ISSUE TITLE
Focus should be loosed when clicking on any other item

### ISSUE THREAD

**Issue by jayudhandha** [gmerabishvili/angular-ng-autocomplete#77]
Hi,

I am using this beautiful library at many places in my project.

But i faced 1 issue recently.

I have 1 button besides the autocomplete textbox. Whenever i select any option i am using it to add in the object.

But, Whenever i type something which is not in the dropdown list. At that time i can't click on the button until i click it twice.

So the 1st click is loosing focus from the autocomplete textbox and 2nd click is actually clicking on that button.

[Demo](https://stackblitz.com/edit/angular-tpara6)

Tye to type anything which is not in the list. Ex: Test

Than try to click on 'Add' button, You will observe that you need to click twice.

Any help?

Thanks,
Jayesh

**Comment by gmerabishvili** [comment]
Hello @jayudhandha Actually that's not even an issue. That's how it should work. You autocomplete is open and it shows "Not found" template. So, you must first close it and then make any other action.
