### ISSUE TITLE
how to clear dropdown after disabling it

### ISSUE THREAD

**Issue by teodoramalec** [gmerabishvili/angular-ng-autocomplete#79]
The functionality of my app is that I can select an option in dropdown and then, the user can disable it.
What I want is to clear the dropdown after disabling it.
I tried with @Viewchild as you sugested in the documentation but didn't work.

Do you have any ideas how to do this? 

ts
```
@ViewChild('cancerDropdown', {static: false}) cancerDropdown;

  clearCancerDropdown() {
    this.cancerDropdown.clear();
  }

```

html
```
  <div class="ng-autocomplete">
          <ng-autocomplete #cancerDropdown
            [data]="cancerChemicals"
            [searchKeyword]="keyword"
            [disabled]="itemInputElementStatus.isCancerChemicalDropdownDisabled"
            (selected)='selectEvent($event)'
            placeHolder="Search Chemical List"
            minQueryLength=3
            [itemTemplate]="itemTemplate"
            [notFoundTemplate]="notFoundTemplate"   
          >
          </ng-autocomplete>

          <ng-template #itemTemplate let-item>
            <a [innerHTML]="item.chemical"></a>
          </ng-template>
        
          <ng-template #notFoundTemplate let-notFound>
            <div [innerHTML]="notFound"></div>
          </ng-template>
      </div>
```

**Comment by teodoramalec** [comment]
my code clears the drop down but opens it after that, and it shouldn't because it's desabled

**Comment by gmerabishvili** [comment]
Hello @teodoramalec you can call close method after clear and it should work. Or please provide Stackblitz example for more details. Thank you.

**Comment by teodoramalec** [comment]
Hi! Thank you for your response. Calling close method worked for the problem. Now, after enabling the autocomplete, I can't open it, like it has no focus. Any ideas why?

**Comment by teodoramalec** [comment]
Thank you, it worked nicely! :)
