### ISSUE TITLE
Can we add custom css on search box ?

### ISSUE THREAD

**Issue by djay007** [gmerabishvili/angular-ng-autocomplete#8]
Hey , 

I was trying to add custom css on  input box but not able to do .  I want to add search svg on input box and want to add border but not able to do. Except input box  i am able to change everything.

Please let me know if i am missing something.

[https://stackblitz.com/edit/angular-tidq88?embed=1&file=src/app/app.component.ts](url)

**Comment by gmerabishvili** [comment]
Hi, your example link is broken. Yes, you can add css on search box as well but you will need to use /deep/  selector. Try and Let me know if everything is OK. Thank you.
