### ISSUE TITLE
ERROR TypeError: "item[this.searchKeyword] is undefined"

### ISSUE THREAD

**Issue by maihannijat** [gmerabishvili/angular-ng-autocomplete#80]
Throws the following error using Angular 9 with angular-ng-autocomplete version 2.0.1:

> ERROR TypeError: "item[this.searchKeyword] is undefined"
```

<ng-autocomplete
  [data]="locations"
  [searchKeyword]="search"
  (selected)='handleResultSelected($event)'
  (inputChanged)='onChangeSearch($event)'
  [itemTemplate]="itemTemplate"
  notFoundText="Not found"
  placeHolder="Search for Location"
  [notFoundTemplate]="notFoundTemplate">
</ng-autocomplete>
<ng-template #itemTemplate let-item>
  <strong>
    {{ item?.city }}{{item?.city ? ',' : ''}} {{item?.adminDistrict}}
  </strong>
</ng-template>

<ng-template #notFoundTemplate let-notFound>
  <div [innerHTML]="notFound"></div>
</ng-template>
```

The logic for calling the data:
```
onChangeSearch(query) {
  if (!query) {
    return;
  }

  this.locationService.searchLocation(query)
    .pipe(
      debounceTime(300),
    ).subscribe(data => {
      this.locations = data;
      this.cd.detectChanges();
    });
}
```

It does not work with the JSON object but does with an Array of strings.

**Comment by gmerabishvili** [comment]
@maihannijat I think you're doing something wrong. Can you provide your issue in Stackblitz please?

**Comment by maihannijat** [comment]
@gmerabishvili I do not get the error in stackblitz but it does not work with JSON objects.
https://stackblitz.com/edit/mn-angular-autocomplete

**Comment by maihannijat** [comment]
I completely misunderstood `[searchKeyword]="keyword"`. I thought it's search term but just realized it's the key name of object.

Closing this. Thanks

**Comment by maihannijat** [comment]
I completely misunderstood `[searchKeyword]="keyword"`. I thought it's search term but just realized it's the key name of the object.

Closing this. Thanks
