### ISSUE TITLE
Issue display wrong initialValue in reactive form

### ISSUE THREAD

**Issue by nntdinh** [gmerabishvili/angular-ng-autocomplete#81]
![image](https://user-images.githubusercontent.com/29629732/76503485-952f9c80-6478-11ea-9815-d22d3cc45c69.png)
It display the whole object instead of only "display" value.
If i don't put initialValue in form group, it doen't show anything in input
And this is my html file
![image](https://user-images.githubusercontent.com/29629732/76503869-361e5780-6479-11ea-849c-edcbff0276e8.png)

**Comment by gmerabishvili** [comment]
@nntdinh You should have item.display in template:     
<ng-template #itemTemplateStatic let-item>
            <a [innerHTML]="item.display"></a>
          </ng-template>

**Comment by nntdinh** [comment]
![image](https://user-images.githubusercontent.com/29629732/76507565-9adcb080-647f-11ea-8538-e463ff565e45.png)
Ah yeah, i forgot that. But it can't fix this problem. I think your suggest only fix the dropdown item display, not the input value display.

**Comment by gmerabishvili** [comment]
BTW you don't need initialValue property while you working with reactive forms: You can use native patchValue method from the Angular Formgroup to set initial value like this:
```
   this.reactiveForm.patchValue({
      id: 1,
      name: 'Albania',
    })
```

**Comment by nntdinh** [comment]
I've tried this way before i used initialValue, it didn't work. I think it doesn't trigger your "select" method, which put the text into "query".
![image](https://user-images.githubusercontent.com/29629732/76509108-117aad80-6482-11ea-8929-66a97f750358.png)

**Comment by gmerabishvili** [comment]
I've tested patchValue and it worked nicely. Can you provide your example in Stackblitz please? I think you're doing something wrong..

**Comment by nntdinh** [comment]
https://stackblitz.com/edit/angular-1gayju
Here is it. Thank you very much.

**Comment by gmerabishvili** [comment]
@nntdinh Here is the link and it works perfectly : )
https://stackblitz.com/edit/angular-ng-autocomplete-with-forms?file=src%2Fapp%2Fapp.component.ts

**Comment by gmerabishvili** [comment]
@nntdinh Try this: https://stackblitz.com/edit/angular-ng-autocomplete-with-forms?file=src%2Fapp%2Fapp.component.ts

**Comment by nntdinh** [comment]
As I mention above, my expected result is:
![image](https://user-images.githubusercontent.com/29629732/76522415-27e03380-6499-11ea-9639-57d939890a27.png)
But actual result is:
![image](https://user-images.githubusercontent.com/29629732/76522475-3890a980-6499-11ea-8326-c0219413bf7a.png)
Could you please check it again, thank you very much.

**Comment by khocef** [comment]
Having the same issue :(

**Comment by kzay** [comment]
Same....

**Comment by manojvarmaboppisetti** [comment]
Same issue for me too. @gmerabishvili can you please provide [value] kind of input decorator to get expected behaviour

**Comment by gmerabishvili** [comment]
Hello @nntdinh @khocef  @kzay @manojvarmaboppisetti The issue is fixed. Please upgrade to latest 2.0.2 version. Thank you!
