### ISSUE TITLE
Fill the autocomplete field with data on init

### ISSUE THREAD

**Issue by khocef** [gmerabishvili/angular-ng-autocomplete#86]
Hi thanks for the package

I have a use case when i want to prefill the autocomlete with a value from an array of objects and its showing [Object Object] instead of the the field of the object

![image](https://user-images.githubusercontent.com/3718899/80308579-1300fa80-87d0-11ea-8734-a02f3a9ed018.png)

Stackblitz demo https://stackblitz.com/edit/angular-ng-autocomplete-with-forms-bejczc

**Comment by lexod** [comment]
had the same issue.
there is one dirty hack you can use in order to make it work without a fix.
```js
constructor(private _fb: FormBuilder) {
    const initial = {id: 1, name:'Armenia'};
    const keyword = this.keyword;
    initial.toString = function(){return this[keyword];};
    this.reactiveForm = _fb.group({
      name: [{value:  initial, disabled: false}, Validators.required]
    });
  }
```

in general, it seem like lib lacks toString method if provided value is an object.

**Comment by khocef** [comment]
@lexod  yes the hack works.
The lib have another issue when using objects in the filterList method
ERROR TypeError: this.query.toLowerCase is not a function because this.query is an object not a string
```javascript
else if (typeof item === 'object' && item.constructor === Object) {
    // object logic, check property equality
    return item[this.searchKeyword].toLowerCase().indexOf(this.query.toLowerCase()) > -1;
 }
```

**Comment by lexod** [comment]
@khocef some modification to my previous snippet should cover your needs
```js
constructor(private _fb: FormBuilder) {
    const keyword = this.keyword;
    const objectDefaults = {toString: function(){return this[keyword];}m toLowerCase: function(){return this.this[keyword].toLowerCase();}} // this.toString() might work as well
    const initial = {...{id: 1, name:'Armenia'}, ...objectDefaults};
    this.reactiveForm = _fb.group({
      name: [{value:  initial, disabled: false}, Validators.required]
    });
  }
```

**Comment by khocef** [comment]
@lexod tanx, but i guess i wont use the lib anymore too much hacks to make it work

**Comment by gmerabishvili** [comment]
@khocef, @lexod Hello, the issue is fixed. Please upgrade to latest 2.0.2 version. Thank you!
