### ISSUE TITLE
cant bind to value since it is not a known property of ng-autocomplete

### ISSUE THREAD

**Issue by ansuhail** [gmerabishvili/angular-ng-autocomplete#87]
hi i am having issue cant bind to value since it is not a known property of ng-autocomplete. I want to use [value] .

**Comment by manojvarmaboppisetti** [comment]
@ansuhail @gmerabishvili even i required similar feature. please provide it

**Comment by gmerabishvili** [comment]
Hello @ansuhail , @manojvarmaboppisetti Why you guys need the value? It doesn't make sense to add another property "value", because you already have everything out of the box regarding the value.

**Comment by manojvarmaboppisetti** [comment]
@gmerabishvili I want to specify what property of object should be bound to formcontrol like the the way it is for select dropdown.
