### ISSUE TITLE
Disable CSS

### ISSUE THREAD

**Issue by venelinn** [gmerabishvili/angular-ng-autocomplete#88]
Hi,
This is great plugin, but I'd like to use my on CSS.
Is there a way to completely disable the CSS?

The reason I'm asking is because I don't like overwriting.

Thank you !

**Comment by gmerabishvili** [comment]
No, you can't disable the css. You have to override with your own styles.

**Comment by marcoziliotto** [comment]
Hi Giorgi, thank you for your great work.
I agree with this request, it would be nice if it were possible to disable the loading of the css, perhaps as an option on the loading of the module.
This would avoid overwriting styles, and above all loading material icons styles files and font files.

Thanks again
Marco
Venice, Italy
