### ISSUE TITLE
Nice to have: Get the selected item when you press tab in a element from the list

### ISSUE THREAD

**Issue by Quethzel** [gmerabishvili/angular-ng-autocomplete#91]
When you get the item list and use the arrow keys to move over the list, it would be a good idea to be able to select the item if you press tab. For now it only works if you press enter.

**Comment by ManuelTS** [comment]
@Quethzel I use tab to navigate through links in the HTML and tab usage is defined in the [Accessible Rich Internet Applications (WAI-ARIA) 1.1 W3C Recommendation](https://www.w3.org/TR/wai-aria-1.1/). So, selection by tab is a bad idea as it would break already established standards in HTML accessibility.

**Comment by gmerabishvili** [comment]
@Quethzel Hello, I agree with @ManuelTS. Thank you.
