### ISSUE TITLE
problem with assign data with server side

### ISSUE THREAD

**Issue by aborndeepak** [gmerabishvili/angular-ng-autocomplete#92]
## - my code
router.get('/',(req,res,)=>{
        res.setHeader('Access-Control-Allow-Origin', 'http://localhost:4200');
        //database query]
        // let city_id = req.params.city_id;
         mysqlConnection.query("SELECT sc.category_id,sc.page_id,cat.category_name FROM services_cities as sc LEFT JOIN service_category as cat ON sc.category_id=cat.id WHERE sc.city_id=1",(err,rows,fields)=>{
             
           if(!err){
                 res.send(rows);
               
             }else{
                 console.log(err);
             }
         })
    })
// this is data in which i stored 
 this.data = this._headerService.getCityService();

`<div class="ng-autocomplete col-8 p-0 my-2 my-md-0 border rounded-right bg-white" >
                            <label for="" class="small px-3 font-weight-bold text-muted mb-0">How may we help you ?{{services}}  </label>
                            <ng-autocomplete 
                            [data]="data"
                            [searchKeyword]="keyword"
                            placeHolder="Enter Service name"
                            (selected)='selectEvent($event)'
                            (inputChanged)='onChangeSearch($event)'
                             (inputFocused)='onFocused($event)'
                             [itemTemplate]="itemTemplate"
                              historyIdentifier="data"
                            >                             
                             </ng-autocomplete>   
                             <ng-template #itemTemplate let-item>
                                  <a [innerHTML]="item.category_name" ></a>
                              </ng-template>
                        </div>`

**Comment by gmerabishvili** [comment]
@aborndeepak What problem are you facing exactly? Can you provide more details please?
