### ISSUE TITLE
<b> is appended in the autocomplete search result

### ISSUE THREAD

**Issue by tech-nerd** [gmerabishvili/angular-ng-autocomplete#94]
<img width="1792" alt="Screenshot 2020-06-21 at 12 05 07 PM" src="https://user-images.githubusercontent.com/57493336/85218426-d577b280-b3b7-11ea-9a96-cccd864ba60e.png">

**Comment by tech-nerd** [comment]
I am using angular-ng-autocomplete for my project, i am facing this issue.

**Comment by gmerabishvili** [comment]
@tech-nerd use innerHTML in template like this:  `<a [innerHTML]="item.name"></a>`

**Comment by tech-nerd** [comment]
thanks for quick support, it worked ✌🏼
