### ISSUE TITLE
keyword from ng-autocomplete not working for me

### ISSUE THREAD

**Issue by marcelopablods** [gmerabishvili/angular-ng-autocomplete#95]
hi, i am trying to filter my cities array by key name of the city object, how would my keyword have to be? I have tried some ways and it always gives me the following error:
![error](https://user-images.githubusercontent.com/48570391/85783100-0710b680-b6f5-11ea-9f32-5f3d31fb91f7.PNG)

here my array 
![xxxx](https://user-images.githubusercontent.com/48570391/85783225-1bed4a00-b6f5-11ea-95b5-5db1cd3b540e.PNG)

Can someone help me please?

**Comment by gmerabishvili** [comment]
Hello @marcelopablods, check the Stackblitz demo please: https://stackblitz.com/edit/angular-ng-autocomplete
