### ISSUE TITLE
Pressing Enter to select first item in the list

### ISSUE THREAD

**Issue by Tonio-lavanda** [gmerabishvili/angular-ng-autocomplete#96]
Hello,

First of all thanks for this component, it works well and it's a fantastic piece of work.

I would like to achieve a behaviour that I think is not possible at the moment: **selecting the first element in the list when the user press the "Enter" Key.**

### Current Behaviour:

When the user starts typing something then press the enter key, it doesn't select anything.

For an item to be selected, the user has to:
 - type something
 - press keydown
 - press enter 

The feedback from my users using your component is that they instinctively press enter when there is only one result left and think it will select the element, but it closes the dropdown.

### Possible solution to select the first element when user press Enter
 1) Add an `@Output` to your angular-ng-autocomplete that is called whenever user press enter (and the parent can deal with this event and choose to do what it wants)
 2) Implement the behaviour I want and control it with a new `@Input` in your angular-ng-autocomplete

**Comment by SimoneMSR** [comment]
I have resolved the same issue by including the ng-complete element in a <form> ad using the form (submit) event

HTML code
````
<form (submit)="onSubmit()">
   <ng-autocomplete>
   </ng-autocomplete>
</form>
````

Typescript code
````
onSubmit(){
   console.log(this.data[0])
}
````

**Comment by gmerabishvili** [comment]
Hello @Tonio-lavanda, this feature will be available in the next version. Thank you! <3

**Comment by gmerabishvili** [comment]
@Tonio-lavanda The feature is implemented. Please upgrade to latest 2.0.2 version and check "focusFirst" property in the docs. Thank you!
