### ISSUE TITLE
memory leak with a big list of options

### ISSUE THREAD

**Issue by WuglyakBolgoink** [gmerabishvili/angular-ng-autocomplete#98]
It will be better to have minimum items in popup list or use Angular CDK Virtual Scrolling...

**Comment by gmerabishvili** [comment]
@WuglyakBolgoink Can you explain the issue in more detail please? Thank you.

**Comment by WuglyakBolgoink** [comment]
@gmerabishvili I have a list with  ~7k items. If I open page with this component then browser stop working about 5-10 seconds, and then the popup dialog for autocomplete is empty with many invisible items... which I can scroll...

**Comment by WuglyakBolgoink** [comment]
![image](https://user-images.githubusercontent.com/2271337/87887198-447e1080-ca23-11ea-9183-911a82e87233.png)
this is minimal example

**Comment by WuglyakBolgoink** [comment]
the virtual scrolling with min-item-count (eg. 10) can avoid the problem with +100500 created elements in DOM

**Comment by gmerabishvili** [comment]
@WuglyakBolgoink Hello, do you use Infinite scroll? Please check the docs. Please try again and let me know if everything works.  I'm closing this issue for now.

**Comment by WuglyakBolgoink** [comment]
Hallo @gmerabishvili !

can you give me an example how I can activate/use infinity scrolling with your plugin? I can't find any information in README file.

**Comment by gmerabishvili** [comment]
Hello @WuglyakBolgoink  you can use (scrolledToEnd) method. Event is emitted when scrolled to the end of items. Can be used for loading more items in chunks.

**Comment by WuglyakBolgoink** [comment]
@gmerabishvili ah.. ok! tnx!
