### ISSUE TITLE
Need enter event on searchbar

### ISSUE THREAD

**Issue by prateekguptadelhi** [gmerabishvili/angular-ng-autocomplete#99]
Give a option to enter on textbar without selection any item from autocomplete, just type something and enter to pass it to other page.

**Comment by gmerabishvili** [comment]
Can you provide more details about your requirement please?

**Comment by ManuelTS** [comment]
@gmerabishvili, I guess @prateekguptadelhi means when you simply type something and then without any other interaction the user hits the enter key. @prateekguptadelhi did not RTFM, sind then he would now that the attribute `(keyup.enter)="onSubmit($event)"` is available. Hence, I say this issue can be closed.

**Comment by gmerabishvili** [comment]
@ManuelTS Thank you!
